-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 15
-- Total Raw Fields: 85
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Profiles: Per-user settings, one row per user. Holds the gentle parameters that drive the daily ritual. This is the ownership root: every owned row points back here through its Owner relationship.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profiles (
  profiles_id                         TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Profiles had no field named 'Id' or ending in 'Id').
);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS account_key TEXT;                                     -- Stable per-user identity key. Maps to user_id in the generated schema. Owned rows reference this value through their Owner relationship.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS display_name TEXT;                                    -- Friendly display name shown in the app. Default Liz. Maps to profile.display_name.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS tagline TEXT;                                         -- Personal tagline. Default Illuminating Life, Legacy, and Love. Maps to profile.tagline.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS weekly_warmup_goal INTEGER;                           -- Target number of hellos per week, shown as encouragement, never a backlog. Default 4. Maps to profile.weekly_warmup_goal. See GovernanceRules R4.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS warm_threshold_days INTEGER;                          -- A person stays Warm within this many days of the last hello. Default 14. Maps to profile.warm_threshold_days. See GovernanceRules R2.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS cooling_threshold_days INTEGER;                       -- A person is Cooling up to this many days since the last hello, then Cold beyond it. Default 30. Maps to profile.cooling_threshold_days. See GovernanceRules R2.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS morning_warmup_count INTEGER;                         -- How many people the Today screen surfaces each morning, one at a time. Default 3. Maps to profile.morning_warmup_count. See GovernanceRules R3.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS week_start TIMESTAMPTZ;                               -- Anchor for the weekly count, set to the most recent Monday. Maps to profile.week_start. See GovernanceRules R4.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS week_count INTEGER;                                   -- Hellos logged since WeekStart, maintained by the app and reset each Monday. Default 0. Maps to profile.week_count.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS people TEXT;                                          -- The people owned by this profile.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS facilities TEXT;                                      -- The facilities owned by this profile.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS captures TEXT;                                        -- The captures owned by this profile.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS o_auth_tokens TEXT;                                   -- The server-side OAuth tokens owned by this profile.
COMMENT ON TABLE profiles IS 'Per-user settings, one row per user. Holds the gentle parameters that drive the daily ritual. This is the ownership root: every owned row points back here through its Owner relationship.';
COMMENT ON COLUMN profiles.profiles_id IS 'Primary key (auto-synthesized: Profiles had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN profiles.account_key IS 'Stable per-user identity key. Maps to user_id in the generated schema. Owned rows reference this value through their Owner relationship.';
COMMENT ON COLUMN profiles.display_name IS 'Friendly display name shown in the app. Default Liz. Maps to profile.display_name.';
COMMENT ON COLUMN profiles.tagline IS 'Personal tagline. Default Illuminating Life, Legacy, and Love. Maps to profile.tagline.';
COMMENT ON COLUMN profiles.weekly_warmup_goal IS 'Target number of hellos per week, shown as encouragement, never a backlog. Default 4. Maps to profile.weekly_warmup_goal. See GovernanceRules R4.';
COMMENT ON COLUMN profiles.warm_threshold_days IS 'A person stays Warm within this many days of the last hello. Default 14. Maps to profile.warm_threshold_days. See GovernanceRules R2.';
COMMENT ON COLUMN profiles.cooling_threshold_days IS 'A person is Cooling up to this many days since the last hello, then Cold beyond it. Default 30. Maps to profile.cooling_threshold_days. See GovernanceRules R2.';
COMMENT ON COLUMN profiles.morning_warmup_count IS 'How many people the Today screen surfaces each morning, one at a time. Default 3. Maps to profile.morning_warmup_count. See GovernanceRules R3.';
COMMENT ON COLUMN profiles.week_start IS 'Anchor for the weekly count, set to the most recent Monday. Maps to profile.week_start. See GovernanceRules R4.';
COMMENT ON COLUMN profiles.week_count IS 'Hellos logged since WeekStart, maintained by the app and reset each Monday. Default 0. Maps to profile.week_count.';
COMMENT ON COLUMN profiles.people IS 'The people owned by this profile.';
COMMENT ON COLUMN profiles.facilities IS 'The facilities owned by this profile.';
COMMENT ON COLUMN profiles.captures IS 'The captures owned by this profile.';
COMMENT ON COLUMN profiles.o_auth_tokens IS 'The server-side OAuth tokens owned by this profile.';

-- ----------------------------------------------------------------------------
-- People: The warm network. Liz's sphere of influence and community ecosystem, anyone who can open a door or help map who is aligned.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS people (
  people_id                           TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: People had no field named 'Id' or ending in 'Id').
);
ALTER TABLE people ADD COLUMN IF NOT EXISTS full_name TEXT;                                         -- The person's name. The only required field on a person. Maps to people.name. See GovernanceRules R6.
ALTER TABLE people ADD COLUMN IF NOT EXISTS owner TEXT;                                             -- The profile that owns this row. Holds the Profiles Name. Drives Row Level Security. Maps to people.user_id. See GovernanceRules R1.
ALTER TABLE people ADD COLUMN IF NOT EXISTS role_org TEXT;                                          -- The person's role or organization. Maps to people.role_org.
ALTER TABLE people ADD COLUMN IF NOT EXISTS sphere TEXT;                                            -- Which sphere of the network this person belongs to. Holds the Spheres Name. Maps to people.sphere.
ALTER TABLE people ADD COLUMN IF NOT EXISTS relationship TEXT;                                      -- How Liz knows this person, in her own words. Maps to people.relationship.
ALTER TABLE people ADD COLUMN IF NOT EXISTS doors_can_open TEXT;                                    -- What doors this person can open or who they can introduce. Maps to people.doors_can_open.
ALTER TABLE people ADD COLUMN IF NOT EXISTS the_ask TEXT;                                           -- The specific ask or next favor, kept human and light. Maps to people.the_ask.
ALTER TABLE people ADD COLUMN IF NOT EXISTS email TEXT;                                             -- Email address, used by the native email compose link. Maps to people.email.
ALTER TABLE people ADD COLUMN IF NOT EXISTS phone TEXT;                                             -- Phone number. Maps to people.phone.
ALTER TABLE people ADD COLUMN IF NOT EXISTS linkedin_url TEXT;                                      -- LinkedIn profile URL, used only for Open in LinkedIn deep links. Maps to people.linkedin_url. See GovernanceRules R10.
ALTER TABLE people ADD COLUMN IF NOT EXISTS status TEXT;                                            -- Where this relationship stands. Holds the PersonStatuses Name. Defaults to to-reach-out. Maps to people.status.
ALTER TABLE people ADD COLUMN IF NOT EXISTS last_touched TIMESTAMPTZ;                               -- Date of the most recent hello. Logging a hello sets this to today. Drives Warmth. Maps to people.last_touched. See GovernanceRules R2 and R3.
ALTER TABLE people ADD COLUMN IF NOT EXISTS next_step TEXT;                                         -- The gentle next step with this person. Maps to people.next_step.
ALTER TABLE people ADD COLUMN IF NOT EXISTS notes TEXT;                                             -- Free notes. Maps to people.notes.
COMMENT ON TABLE people IS 'The warm network. Liz''s sphere of influence and community ecosystem, anyone who can open a door or help map who is aligned.';
COMMENT ON COLUMN people.people_id IS 'Primary key (auto-synthesized: People had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN people.full_name IS 'The person''s name. The only required field on a person. Maps to people.name. See GovernanceRules R6.';
COMMENT ON COLUMN people.owner IS 'The profile that owns this row. Holds the Profiles Name. Drives Row Level Security. Maps to people.user_id. See GovernanceRules R1.';
COMMENT ON COLUMN people.role_org IS 'The person''s role or organization. Maps to people.role_org.';
COMMENT ON COLUMN people.sphere IS 'Which sphere of the network this person belongs to. Holds the Spheres Name. Maps to people.sphere.';
COMMENT ON COLUMN people.relationship IS 'How Liz knows this person, in her own words. Maps to people.relationship.';
COMMENT ON COLUMN people.doors_can_open IS 'What doors this person can open or who they can introduce. Maps to people.doors_can_open.';
COMMENT ON COLUMN people.the_ask IS 'The specific ask or next favor, kept human and light. Maps to people.the_ask.';
COMMENT ON COLUMN people.email IS 'Email address, used by the native email compose link. Maps to people.email.';
COMMENT ON COLUMN people.phone IS 'Phone number. Maps to people.phone.';
COMMENT ON COLUMN people.linkedin_url IS 'LinkedIn profile URL, used only for Open in LinkedIn deep links. Maps to people.linkedin_url. See GovernanceRules R10.';
COMMENT ON COLUMN people.status IS 'Where this relationship stands. Holds the PersonStatuses Name. Defaults to to-reach-out. Maps to people.status.';
COMMENT ON COLUMN people.last_touched IS 'Date of the most recent hello. Logging a hello sets this to today. Drives Warmth. Maps to people.last_touched. See GovernanceRules R2 and R3.';
COMMENT ON COLUMN people.next_step IS 'The gentle next step with this person. Maps to people.next_step.';
COMMENT ON COLUMN people.notes IS 'Free notes. Maps to people.notes.';

-- ----------------------------------------------------------------------------
-- Facilities: The target places. Values aligned independent living and 55 and over communities first, the places Liz is working toward.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS facilities (
  facilities_id                       TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Facilities had no field named 'Id' or ending in 'Id').
);
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS facility_name TEXT;                                 -- The facility name. The only required field on a facility. Maps to facilities.facility_name. See GovernanceRules R6.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS owner TEXT;                                         -- The profile that owns this row. Holds the Profiles Name. Drives Row Level Security. Maps to facilities.user_id. See GovernanceRules R1.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS type TEXT;                                          -- The kind of facility. Holds the FacilityTypes Name. Maps to facilities.type.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS town TEXT;                                          -- Town where the facility is located. Maps to facilities.town.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS region TEXT;                                        -- Region grouping for the facility. Holds the Regions Name. Maps to facilities.region.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS lead_route TEXT;                                    -- How Liz can reach this facility, warm or cold. Holds the LeadRoutes Name. Maps to facilities.lead_route.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS aligned TEXT;                                       -- Whether the facility seems values aligned. Holds the AlignmentLevels Name. Maps to facilities.aligned.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS decision_maker TEXT;                                -- Name of the person who decides. Maps to facilities.decision_maker.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS title TEXT;                                         -- Title of the decision maker. Maps to facilities.title.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS email TEXT;                                         -- Contact email. Maps to facilities.email.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS phone TEXT;                                         -- Contact phone. Maps to facilities.phone.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS website TEXT;                                       -- Facility website. Maps to facilities.website.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS status TEXT;                                        -- Where the outreach stands. Holds the FacilityStatuses Name. Defaults to to-research. Maps to facilities.status.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS next_step TEXT;                                     -- The gentle next step with this facility. Maps to facilities.next_step.
ALTER TABLE facilities ADD COLUMN IF NOT EXISTS fit_notes TEXT;                                     -- Notes on fit and alignment. Maps to facilities.fit_notes.
COMMENT ON TABLE facilities IS 'The target places. Values aligned independent living and 55 and over communities first, the places Liz is working toward.';
COMMENT ON COLUMN facilities.facilities_id IS 'Primary key (auto-synthesized: Facilities had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN facilities.facility_name IS 'The facility name. The only required field on a facility. Maps to facilities.facility_name. See GovernanceRules R6.';
COMMENT ON COLUMN facilities.owner IS 'The profile that owns this row. Holds the Profiles Name. Drives Row Level Security. Maps to facilities.user_id. See GovernanceRules R1.';
COMMENT ON COLUMN facilities.type IS 'The kind of facility. Holds the FacilityTypes Name. Maps to facilities.type.';
COMMENT ON COLUMN facilities.town IS 'Town where the facility is located. Maps to facilities.town.';
COMMENT ON COLUMN facilities.region IS 'Region grouping for the facility. Holds the Regions Name. Maps to facilities.region.';
COMMENT ON COLUMN facilities.lead_route IS 'How Liz can reach this facility, warm or cold. Holds the LeadRoutes Name. Maps to facilities.lead_route.';
COMMENT ON COLUMN facilities.aligned IS 'Whether the facility seems values aligned. Holds the AlignmentLevels Name. Maps to facilities.aligned.';
COMMENT ON COLUMN facilities.decision_maker IS 'Name of the person who decides. Maps to facilities.decision_maker.';
COMMENT ON COLUMN facilities.title IS 'Title of the decision maker. Maps to facilities.title.';
COMMENT ON COLUMN facilities.email IS 'Contact email. Maps to facilities.email.';
COMMENT ON COLUMN facilities.phone IS 'Contact phone. Maps to facilities.phone.';
COMMENT ON COLUMN facilities.website IS 'Facility website. Maps to facilities.website.';
COMMENT ON COLUMN facilities.status IS 'Where the outreach stands. Holds the FacilityStatuses Name. Defaults to to-research. Maps to facilities.status.';
COMMENT ON COLUMN facilities.next_step IS 'The gentle next step with this facility. Maps to facilities.next_step.';
COMMENT ON COLUMN facilities.fit_notes IS 'Notes on fit and alignment. Maps to facilities.fit_notes.';

-- ----------------------------------------------------------------------------
-- Captures: Pain points, case studies, and ideas, captured as they come. Feeds the marketing package.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS captures (
  captures_id                         TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Captures had no field named 'Id' or ending in 'Id').
);
ALTER TABLE captures ADD COLUMN IF NOT EXISTS title TEXT;                                           -- Short title of the capture. The only required field on a capture. Maps to captures.title. See GovernanceRules R6.
ALTER TABLE captures ADD COLUMN IF NOT EXISTS owner TEXT;                                           -- The profile that owns this row. Holds the Profiles Name. Drives Row Level Security. Maps to captures.user_id. See GovernanceRules R1.
ALTER TABLE captures ADD COLUMN IF NOT EXISTS type TEXT;                                            -- The kind of capture. Holds the CaptureTypes Name. Defaults to idea. Maps to captures.type.
ALTER TABLE captures ADD COLUMN IF NOT EXISTS detail TEXT;                                          -- The full text of the capture. Maps to captures.detail.
COMMENT ON TABLE captures IS 'Pain points, case studies, and ideas, captured as they come. Feeds the marketing package.';
COMMENT ON COLUMN captures.captures_id IS 'Primary key (auto-synthesized: Captures had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN captures.title IS 'Short title of the capture. The only required field on a capture. Maps to captures.title. See GovernanceRules R6.';
COMMENT ON COLUMN captures.owner IS 'The profile that owns this row. Holds the Profiles Name. Drives Row Level Security. Maps to captures.user_id. See GovernanceRules R1.';
COMMENT ON COLUMN captures.type IS 'The kind of capture. Holds the CaptureTypes Name. Defaults to idea. Maps to captures.type.';
COMMENT ON COLUMN captures.detail IS 'The full text of the capture. Maps to captures.detail.';

-- ----------------------------------------------------------------------------
-- OAuthTokens: Server-side storage for Drive, LinkedIn, and optional Calendar and Gmail tokens. Never exposed to the client. Read and refreshed only in server code. See GovernanceRules R12.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS o_auth_tokens (
  o_auth_tokens_id                    TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: OAuthTokens had no field named 'Id' or ending in 'Id').
);
ALTER TABLE o_auth_tokens ADD COLUMN IF NOT EXISTS owner TEXT;                                      -- The profile that owns this token. Holds the Profiles Name. Maps to oauth_tokens.user_id. See GovernanceRules R1.
ALTER TABLE o_auth_tokens ADD COLUMN IF NOT EXISTS provider TEXT;                                   -- The integration this token is for, for example google-drive, linkedin, google-calendar, or gmail. Maps to oauth_tokens.provider.
ALTER TABLE o_auth_tokens ADD COLUMN IF NOT EXISTS access_token TEXT;                               -- Short lived access token. Server-side only, never sent to the client. Maps to oauth_tokens.access_token. See GovernanceRules R12.
ALTER TABLE o_auth_tokens ADD COLUMN IF NOT EXISTS refresh_token TEXT;                              -- Long lived refresh token, stored encrypted and tied to the owner. Server-side only. Maps to oauth_tokens.refresh_token. See GovernanceRules R12.
ALTER TABLE o_auth_tokens ADD COLUMN IF NOT EXISTS scope TEXT;                                      -- The granted OAuth scope, kept as narrow as the feature needs. Maps to oauth_tokens.scope. See GovernanceRules R11.
ALTER TABLE o_auth_tokens ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;                          -- When the access token expires. Maps to oauth_tokens.expires_at.
COMMENT ON TABLE o_auth_tokens IS 'Server-side storage for Drive, LinkedIn, and optional Calendar and Gmail tokens. Never exposed to the client. Read and refreshed only in server code. See GovernanceRules R12.';
COMMENT ON COLUMN o_auth_tokens.o_auth_tokens_id IS 'Primary key (auto-synthesized: OAuthTokens had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN o_auth_tokens.owner IS 'The profile that owns this token. Holds the Profiles Name. Maps to oauth_tokens.user_id. See GovernanceRules R1.';
COMMENT ON COLUMN o_auth_tokens.provider IS 'The integration this token is for, for example google-drive, linkedin, google-calendar, or gmail. Maps to oauth_tokens.provider.';
COMMENT ON COLUMN o_auth_tokens.access_token IS 'Short lived access token. Server-side only, never sent to the client. Maps to oauth_tokens.access_token. See GovernanceRules R12.';
COMMENT ON COLUMN o_auth_tokens.refresh_token IS 'Long lived refresh token, stored encrypted and tied to the owner. Server-side only. Maps to oauth_tokens.refresh_token. See GovernanceRules R12.';
COMMENT ON COLUMN o_auth_tokens.scope IS 'The granted OAuth scope, kept as narrow as the feature needs. Maps to oauth_tokens.scope. See GovernanceRules R11.';
COMMENT ON COLUMN o_auth_tokens.expires_at IS 'When the access token expires. Maps to oauth_tokens.expires_at.';

-- ----------------------------------------------------------------------------
-- Spheres: Controlled vocabulary for people.sphere. The part of the network a person belongs to. Generated as a derivative enum table. Do not hardcode these in the frontend or schema.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS spheres (
  spheres_id                          TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Spheres had no field named 'Id' or ending in 'Id').
);
ALTER TABLE spheres ADD COLUMN IF NOT EXISTS sphere_label TEXT;                                     -- Human readable sphere label shown in the app.
ALTER TABLE spheres ADD COLUMN IF NOT EXISTS description TEXT;                                      -- What this sphere means.
ALTER TABLE spheres ADD COLUMN IF NOT EXISTS sort_order INTEGER;                                    -- Display order in pickers.
ALTER TABLE spheres ADD COLUMN IF NOT EXISTS people TEXT;                                           -- People in this sphere.
COMMENT ON TABLE spheres IS 'Controlled vocabulary for people.sphere. The part of the network a person belongs to. Generated as a derivative enum table. Do not hardcode these in the frontend or schema.';
COMMENT ON COLUMN spheres.spheres_id IS 'Primary key (auto-synthesized: Spheres had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN spheres.sphere_label IS 'Human readable sphere label shown in the app.';
COMMENT ON COLUMN spheres.description IS 'What this sphere means.';
COMMENT ON COLUMN spheres.sort_order IS 'Display order in pickers.';
COMMENT ON COLUMN spheres.people IS 'People in this sphere.';

-- ----------------------------------------------------------------------------
-- PersonStatuses: Controlled vocabulary for people.status. Where a relationship stands. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS person_statuses (
  person_statuses_id                  TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: PersonStatuses had no field named 'Id' or ending in 'Id').
);
ALTER TABLE person_statuses ADD COLUMN IF NOT EXISTS status_label TEXT;                             -- Human readable status label shown in the app.
ALTER TABLE person_statuses ADD COLUMN IF NOT EXISTS description TEXT;                              -- What this status means.
ALTER TABLE person_statuses ADD COLUMN IF NOT EXISTS sort_order INTEGER;                            -- Display order in pickers.
ALTER TABLE person_statuses ADD COLUMN IF NOT EXISTS people TEXT;                                   -- People at this status.
COMMENT ON TABLE person_statuses IS 'Controlled vocabulary for people.status. Where a relationship stands. Generated as a derivative enum table.';
COMMENT ON COLUMN person_statuses.person_statuses_id IS 'Primary key (auto-synthesized: PersonStatuses had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN person_statuses.status_label IS 'Human readable status label shown in the app.';
COMMENT ON COLUMN person_statuses.description IS 'What this status means.';
COMMENT ON COLUMN person_statuses.sort_order IS 'Display order in pickers.';
COMMENT ON COLUMN person_statuses.people IS 'People at this status.';

-- ----------------------------------------------------------------------------
-- FacilityTypes: Controlled vocabulary for facilities.type. The kind of place. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS facility_types (
  facility_types_id                   TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: FacilityTypes had no field named 'Id' or ending in 'Id').
);
ALTER TABLE facility_types ADD COLUMN IF NOT EXISTS type_label TEXT;                                -- Human readable facility type label shown in the app.
ALTER TABLE facility_types ADD COLUMN IF NOT EXISTS description TEXT;                               -- What this facility type means.
ALTER TABLE facility_types ADD COLUMN IF NOT EXISTS sort_order INTEGER;                             -- Display order in pickers.
ALTER TABLE facility_types ADD COLUMN IF NOT EXISTS facilities TEXT;                                -- Facilities of this type.
COMMENT ON TABLE facility_types IS 'Controlled vocabulary for facilities.type. The kind of place. Generated as a derivative enum table.';
COMMENT ON COLUMN facility_types.facility_types_id IS 'Primary key (auto-synthesized: FacilityTypes had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN facility_types.type_label IS 'Human readable facility type label shown in the app.';
COMMENT ON COLUMN facility_types.description IS 'What this facility type means.';
COMMENT ON COLUMN facility_types.sort_order IS 'Display order in pickers.';
COMMENT ON COLUMN facility_types.facilities IS 'Facilities of this type.';

-- ----------------------------------------------------------------------------
-- Regions: Controlled vocabulary for facilities.region. Geographic grouping. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS regions (
  regions_id                          TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Regions had no field named 'Id' or ending in 'Id').
);
ALTER TABLE regions ADD COLUMN IF NOT EXISTS region_label TEXT;                                     -- Human readable region label shown in the app.
ALTER TABLE regions ADD COLUMN IF NOT EXISTS description TEXT;                                      -- What this region covers.
ALTER TABLE regions ADD COLUMN IF NOT EXISTS sort_order INTEGER;                                    -- Display order in pickers.
ALTER TABLE regions ADD COLUMN IF NOT EXISTS facilities TEXT;                                       -- Facilities in this region.
COMMENT ON TABLE regions IS 'Controlled vocabulary for facilities.region. Geographic grouping. Generated as a derivative enum table.';
COMMENT ON COLUMN regions.regions_id IS 'Primary key (auto-synthesized: Regions had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN regions.region_label IS 'Human readable region label shown in the app.';
COMMENT ON COLUMN regions.description IS 'What this region covers.';
COMMENT ON COLUMN regions.sort_order IS 'Display order in pickers.';
COMMENT ON COLUMN regions.facilities IS 'Facilities in this region.';

-- ----------------------------------------------------------------------------
-- LeadRoutes: Controlled vocabulary for facilities.lead_route. How Liz can reach a facility. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lead_routes (
  lead_routes_id                      TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: LeadRoutes had no field named 'Id' or ending in 'Id').
);
ALTER TABLE lead_routes ADD COLUMN IF NOT EXISTS lead_route_label TEXT;                             -- Human readable lead route label shown in the app.
ALTER TABLE lead_routes ADD COLUMN IF NOT EXISTS description TEXT;                                  -- What this lead route means.
ALTER TABLE lead_routes ADD COLUMN IF NOT EXISTS sort_order INTEGER;                                -- Display order in pickers.
ALTER TABLE lead_routes ADD COLUMN IF NOT EXISTS facilities TEXT;                                   -- Facilities reached through this route.
COMMENT ON TABLE lead_routes IS 'Controlled vocabulary for facilities.lead_route. How Liz can reach a facility. Generated as a derivative enum table.';
COMMENT ON COLUMN lead_routes.lead_routes_id IS 'Primary key (auto-synthesized: LeadRoutes had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN lead_routes.lead_route_label IS 'Human readable lead route label shown in the app.';
COMMENT ON COLUMN lead_routes.description IS 'What this lead route means.';
COMMENT ON COLUMN lead_routes.sort_order IS 'Display order in pickers.';
COMMENT ON COLUMN lead_routes.facilities IS 'Facilities reached through this route.';

-- ----------------------------------------------------------------------------
-- AlignmentLevels: Controlled vocabulary for facilities.aligned. Whether a facility seems values aligned. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alignment_levels (
  alignment_levels_id                 TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: AlignmentLevels had no field named 'Id' or ending in 'Id').
);
ALTER TABLE alignment_levels ADD COLUMN IF NOT EXISTS alignment_label TEXT;                         -- Human readable alignment label shown in the app.
ALTER TABLE alignment_levels ADD COLUMN IF NOT EXISTS description TEXT;                             -- What this alignment level means.
ALTER TABLE alignment_levels ADD COLUMN IF NOT EXISTS sort_order INTEGER;                           -- Display order in pickers.
ALTER TABLE alignment_levels ADD COLUMN IF NOT EXISTS facilities TEXT;                              -- Facilities at this alignment level.
COMMENT ON TABLE alignment_levels IS 'Controlled vocabulary for facilities.aligned. Whether a facility seems values aligned. Generated as a derivative enum table.';
COMMENT ON COLUMN alignment_levels.alignment_levels_id IS 'Primary key (auto-synthesized: AlignmentLevels had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN alignment_levels.alignment_label IS 'Human readable alignment label shown in the app.';
COMMENT ON COLUMN alignment_levels.description IS 'What this alignment level means.';
COMMENT ON COLUMN alignment_levels.sort_order IS 'Display order in pickers.';
COMMENT ON COLUMN alignment_levels.facilities IS 'Facilities at this alignment level.';

-- ----------------------------------------------------------------------------
-- FacilityStatuses: Controlled vocabulary for facilities.status. Where the outreach stands. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS facility_statuses (
  facility_statuses_id                TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: FacilityStatuses had no field named 'Id' or ending in 'Id').
);
ALTER TABLE facility_statuses ADD COLUMN IF NOT EXISTS status_label TEXT;                           -- Human readable facility status label shown in the app.
ALTER TABLE facility_statuses ADD COLUMN IF NOT EXISTS description TEXT;                            -- What this facility status means.
ALTER TABLE facility_statuses ADD COLUMN IF NOT EXISTS sort_order INTEGER;                          -- Display order in pickers.
ALTER TABLE facility_statuses ADD COLUMN IF NOT EXISTS facilities TEXT;                             -- Facilities at this status.
COMMENT ON TABLE facility_statuses IS 'Controlled vocabulary for facilities.status. Where the outreach stands. Generated as a derivative enum table.';
COMMENT ON COLUMN facility_statuses.facility_statuses_id IS 'Primary key (auto-synthesized: FacilityStatuses had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN facility_statuses.status_label IS 'Human readable facility status label shown in the app.';
COMMENT ON COLUMN facility_statuses.description IS 'What this facility status means.';
COMMENT ON COLUMN facility_statuses.sort_order IS 'Display order in pickers.';
COMMENT ON COLUMN facility_statuses.facilities IS 'Facilities at this status.';

-- ----------------------------------------------------------------------------
-- CaptureTypes: Controlled vocabulary for captures.type. The kind of capture. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS capture_types (
  capture_types_id                    TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: CaptureTypes had no field named 'Id' or ending in 'Id').
);
ALTER TABLE capture_types ADD COLUMN IF NOT EXISTS type_label TEXT;                                 -- Human readable capture type label shown in the app.
ALTER TABLE capture_types ADD COLUMN IF NOT EXISTS description TEXT;                                -- What this capture type means.
ALTER TABLE capture_types ADD COLUMN IF NOT EXISTS sort_order INTEGER;                              -- Display order in pickers.
ALTER TABLE capture_types ADD COLUMN IF NOT EXISTS captures TEXT;                                   -- Captures of this type.
COMMENT ON TABLE capture_types IS 'Controlled vocabulary for captures.type. The kind of capture. Generated as a derivative enum table.';
COMMENT ON COLUMN capture_types.capture_types_id IS 'Primary key (auto-synthesized: CaptureTypes had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN capture_types.type_label IS 'Human readable capture type label shown in the app.';
COMMENT ON COLUMN capture_types.description IS 'What this capture type means.';
COMMENT ON COLUMN capture_types.sort_order IS 'Display order in pickers.';
COMMENT ON COLUMN capture_types.captures IS 'Captures of this type.';

-- ----------------------------------------------------------------------------
-- WarmthLevels: Controlled vocabulary for the derived warmth value. Warmth is computed from LastTouched and is not stored. These rows give the frontend the labels and gentle framing for each level. See GovernanceRules R2 and R5.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS warmth_levels (
  warmth_levels_id                    TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: WarmthLevels had no field named 'Id' or ending in 'Id').
);
ALTER TABLE warmth_levels ADD COLUMN IF NOT EXISTS warmth_label TEXT;                               -- Human readable warmth label shown in the app.
ALTER TABLE warmth_levels ADD COLUMN IF NOT EXISTS description TEXT;                                -- What this warmth level means.
ALTER TABLE warmth_levels ADD COLUMN IF NOT EXISTS guidance TEXT;                                   -- Gentle framing shown to Liz. No guilt, a cold contact reads as ready for a hello. See GovernanceRules R5.
ALTER TABLE warmth_levels ADD COLUMN IF NOT EXISTS sort_order INTEGER;                              -- Display order, warmest first.
COMMENT ON TABLE warmth_levels IS 'Controlled vocabulary for the derived warmth value. Warmth is computed from LastTouched and is not stored. These rows give the frontend the labels and gentle framing for each level. See GovernanceRules R2 and R5.';
COMMENT ON COLUMN warmth_levels.warmth_levels_id IS 'Primary key (auto-synthesized: WarmthLevels had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN warmth_levels.warmth_label IS 'Human readable warmth label shown in the app.';
COMMENT ON COLUMN warmth_levels.description IS 'What this warmth level means.';
COMMENT ON COLUMN warmth_levels.guidance IS 'Gentle framing shown to Liz. No guilt, a cold contact reads as ready for a hello. See GovernanceRules R5.';
COMMENT ON COLUMN warmth_levels.sort_order IS 'Display order, warmest first.';

-- ----------------------------------------------------------------------------
-- GovernanceRules: The governance rules for the BeaconHaus Companion, one row per rule. Each rule is meaning that lives in the rulebook and is traceable. The frontend and backend enforce these because they are generated from them, not because someone wrote them into code by hand.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS governance_rules (
  governance_rules_id                 TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: GovernanceRules had no field named 'Id' or ending in 'Id').
);
ALTER TABLE governance_rules ADD COLUMN IF NOT EXISTS rule_code TEXT;                               -- Short rule code, R1 through R12.
ALTER TABLE governance_rules ADD COLUMN IF NOT EXISTS title TEXT;                                   -- Short title of the rule.
ALTER TABLE governance_rules ADD COLUMN IF NOT EXISTS statement TEXT;                               -- The full rule statement, the meaning that downstream artifacts must honor.
ALTER TABLE governance_rules ADD COLUMN IF NOT EXISTS category TEXT;                                -- Grouping for the rule, for example Ownership, Warmth, Ritual, Content, Positioning, Integration, Security, or UX.
ALTER TABLE governance_rules ADD COLUMN IF NOT EXISTS enforced_by TEXT;                             -- Where this rule is realized in the derivative outputs.
ALTER TABLE governance_rules ADD COLUMN IF NOT EXISTS sort_order INTEGER;                           -- Display order, R1 through R12.
COMMENT ON TABLE governance_rules IS 'The governance rules for the BeaconHaus Companion, one row per rule. Each rule is meaning that lives in the rulebook and is traceable. The frontend and backend enforce these because they are generated from them, not because someone wrote them into code by hand.';
COMMENT ON COLUMN governance_rules.governance_rules_id IS 'Primary key (auto-synthesized: GovernanceRules had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN governance_rules.rule_code IS 'Short rule code, R1 through R12.';
COMMENT ON COLUMN governance_rules.title IS 'Short title of the rule.';
COMMENT ON COLUMN governance_rules.statement IS 'The full rule statement, the meaning that downstream artifacts must honor.';
COMMENT ON COLUMN governance_rules.category IS 'Grouping for the rule, for example Ownership, Warmth, Ritual, Content, Positioning, Integration, Security, or UX.';
COMMENT ON COLUMN governance_rules.enforced_by IS 'Where this rule is realized in the derivative outputs.';
COMMENT ON COLUMN governance_rules.sort_order IS 'Display order, R1 through R12.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- Profiles
CREATE INDEX IF NOT EXISTS idx_profiles_people ON profiles (people);
CREATE INDEX IF NOT EXISTS idx_profiles_facilities ON profiles (facilities);
CREATE INDEX IF NOT EXISTS idx_profiles_captures ON profiles (captures);
CREATE INDEX IF NOT EXISTS idx_profiles_o_auth_tokens ON profiles (o_auth_tokens);

-- People
CREATE INDEX IF NOT EXISTS idx_people_owner ON people (owner);
CREATE INDEX IF NOT EXISTS idx_people_sphere ON people (sphere);
CREATE INDEX IF NOT EXISTS idx_people_status ON people (status);

-- Facilities
CREATE INDEX IF NOT EXISTS idx_facilities_owner ON facilities (owner);
CREATE INDEX IF NOT EXISTS idx_facilities_type ON facilities (type);
CREATE INDEX IF NOT EXISTS idx_facilities_region ON facilities (region);
CREATE INDEX IF NOT EXISTS idx_facilities_lead_route ON facilities (lead_route);
CREATE INDEX IF NOT EXISTS idx_facilities_aligned ON facilities (aligned);
CREATE INDEX IF NOT EXISTS idx_facilities_status ON facilities (status);

-- Captures
CREATE INDEX IF NOT EXISTS idx_captures_owner ON captures (owner);
CREATE INDEX IF NOT EXISTS idx_captures_type ON captures (type);

-- OAuthTokens
CREATE INDEX IF NOT EXISTS idx_o_auth_tokens_owner ON o_auth_tokens (owner);

-- Spheres
CREATE INDEX IF NOT EXISTS idx_spheres_people ON spheres (people);

-- PersonStatuses
CREATE INDEX IF NOT EXISTS idx_person_statuses_people ON person_statuses (people);

-- FacilityTypes
CREATE INDEX IF NOT EXISTS idx_facility_types_facilities ON facility_types (facilities);

-- Regions
CREATE INDEX IF NOT EXISTS idx_regions_facilities ON regions (facilities);

-- LeadRoutes
CREATE INDEX IF NOT EXISTS idx_lead_routes_facilities ON lead_routes (facilities);

-- AlignmentLevels
CREATE INDEX IF NOT EXISTS idx_alignment_levels_facilities ON alignment_levels (facilities);

-- FacilityStatuses
CREATE INDEX IF NOT EXISTS idx_facility_statuses_facilities ON facility_statuses (facilities);

-- CaptureTypes
CREATE INDEX IF NOT EXISTS idx_capture_types_captures ON capture_types (captures);

-- 24 FK index(es) declared.
