-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- get_people_full_name
-- Helper function: Get FullName from People by PeopleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_people_full_name(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name FROM people WHERE people_id = p_people_id);
$$ LANGUAGE sql STABLE;

-- get_people_role_org
-- Helper function: Get RoleOrg from People by PeopleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_people_role_org(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT role_org FROM people WHERE people_id = p_people_id);
$$ LANGUAGE sql STABLE;

-- get_people_relationship
-- Helper function: Get Relationship from People by PeopleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_people_relationship(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT relationship FROM people WHERE people_id = p_people_id);
$$ LANGUAGE sql STABLE;

-- get_people_doors_can_open
-- Helper function: Get DoorsCanOpen from People by PeopleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_people_doors_can_open(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT doors_can_open FROM people WHERE people_id = p_people_id);
$$ LANGUAGE sql STABLE;

-- get_people_the_ask
-- Helper function: Get TheAsk from People by PeopleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_people_the_ask(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT the_ask FROM people WHERE people_id = p_people_id);
$$ LANGUAGE sql STABLE;

-- get_people_email
-- Helper function: Get Email from People by PeopleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_people_email(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT email FROM people WHERE people_id = p_people_id);
$$ LANGUAGE sql STABLE;

-- get_people_phone
-- Helper function: Get Phone from People by PeopleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_people_phone(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT phone FROM people WHERE people_id = p_people_id);
$$ LANGUAGE sql STABLE;

-- get_people_linkedin_url
-- Helper function: Get LinkedinUrl from People by PeopleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_people_linkedin_url(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT linkedin_url FROM people WHERE people_id = p_people_id);
$$ LANGUAGE sql STABLE;

-- get_people_last_touched
-- Helper function: Get LastTouched from People by PeopleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_people_last_touched(p_people_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT last_touched FROM people WHERE people_id = p_people_id);
$$ LANGUAGE sql STABLE;

-- get_people_next_step
-- Helper function: Get NextStep from People by PeopleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_people_next_step(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT next_step FROM people WHERE people_id = p_people_id);
$$ LANGUAGE sql STABLE;

-- get_people_notes
-- Helper function: Get Notes from People by PeopleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_people_notes(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT notes FROM people WHERE people_id = p_people_id);
$$ LANGUAGE sql STABLE;

-- get_facilities_facility_name
-- Helper function: Get FacilityName from Facilities by FacilitiesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facilities_facility_name(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT facility_name FROM facilities WHERE facilities_id = p_facilities_id);
$$ LANGUAGE sql STABLE;

-- get_facilities_town
-- Helper function: Get Town from Facilities by FacilitiesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facilities_town(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT town FROM facilities WHERE facilities_id = p_facilities_id);
$$ LANGUAGE sql STABLE;

-- get_facilities_decision_maker
-- Helper function: Get DecisionMaker from Facilities by FacilitiesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facilities_decision_maker(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT decision_maker FROM facilities WHERE facilities_id = p_facilities_id);
$$ LANGUAGE sql STABLE;

-- get_facilities_title
-- Helper function: Get Title from Facilities by FacilitiesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facilities_title(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM facilities WHERE facilities_id = p_facilities_id);
$$ LANGUAGE sql STABLE;

-- get_facilities_email
-- Helper function: Get Email from Facilities by FacilitiesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facilities_email(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT email FROM facilities WHERE facilities_id = p_facilities_id);
$$ LANGUAGE sql STABLE;

-- get_facilities_phone
-- Helper function: Get Phone from Facilities by FacilitiesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facilities_phone(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT phone FROM facilities WHERE facilities_id = p_facilities_id);
$$ LANGUAGE sql STABLE;

-- get_facilities_website
-- Helper function: Get Website from Facilities by FacilitiesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facilities_website(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT website FROM facilities WHERE facilities_id = p_facilities_id);
$$ LANGUAGE sql STABLE;

-- get_facilities_next_step
-- Helper function: Get NextStep from Facilities by FacilitiesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facilities_next_step(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT next_step FROM facilities WHERE facilities_id = p_facilities_id);
$$ LANGUAGE sql STABLE;

-- get_facilities_fit_notes
-- Helper function: Get FitNotes from Facilities by FacilitiesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facilities_fit_notes(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT fit_notes FROM facilities WHERE facilities_id = p_facilities_id);
$$ LANGUAGE sql STABLE;

-- get_captures_title
-- Helper function: Get Title from Captures by CapturesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_captures_title(p_captures_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM captures WHERE captures_id = p_captures_id);
$$ LANGUAGE sql STABLE;

-- get_captures_detail
-- Helper function: Get Detail from Captures by CapturesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_captures_detail(p_captures_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT detail FROM captures WHERE captures_id = p_captures_id);
$$ LANGUAGE sql STABLE;

-- get_o_auth_tokens_provider
-- Helper function: Get Provider from OAuthTokens by OAuthTokensId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_o_auth_tokens_provider(p_o_auth_tokens_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT provider FROM o_auth_tokens WHERE o_auth_tokens_id = p_o_auth_tokens_id);
$$ LANGUAGE sql STABLE;

-- get_o_auth_tokens_access_token
-- Helper function: Get AccessToken from OAuthTokens by OAuthTokensId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_o_auth_tokens_access_token(p_o_auth_tokens_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT access_token FROM o_auth_tokens WHERE o_auth_tokens_id = p_o_auth_tokens_id);
$$ LANGUAGE sql STABLE;

-- get_o_auth_tokens_refresh_token
-- Helper function: Get RefreshToken from OAuthTokens by OAuthTokensId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_o_auth_tokens_refresh_token(p_o_auth_tokens_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT refresh_token FROM o_auth_tokens WHERE o_auth_tokens_id = p_o_auth_tokens_id);
$$ LANGUAGE sql STABLE;

-- get_o_auth_tokens_scope
-- Helper function: Get Scope from OAuthTokens by OAuthTokensId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_o_auth_tokens_scope(p_o_auth_tokens_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT scope FROM o_auth_tokens WHERE o_auth_tokens_id = p_o_auth_tokens_id);
$$ LANGUAGE sql STABLE;

-- get_o_auth_tokens_expires_at
-- Helper function: Get ExpiresAt from OAuthTokens by OAuthTokensId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_o_auth_tokens_expires_at(p_o_auth_tokens_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT expires_at FROM o_auth_tokens WHERE o_auth_tokens_id = p_o_auth_tokens_id);
$$ LANGUAGE sql STABLE;

-- calc_profiles_name
-- Field: Profiles.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_profiles_name(p_profiles_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(account_key, '') FROM profiles WHERE profiles_id = p_profiles_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_profiles_count_of_people
-- Field: Profiles.CountOfPeople
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_profiles_count_of_people(p_profiles_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM people WHERE owner = calc_profiles_name(p_profiles_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_profiles_count_of_facilities
-- Field: Profiles.CountOfFacilities
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_profiles_count_of_facilities(p_profiles_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM facilities WHERE owner = calc_profiles_name(p_profiles_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_profiles_count_of_captures
-- Field: Profiles.CountOfCaptures
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_profiles_count_of_captures(p_profiles_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM captures WHERE owner = calc_profiles_name(p_profiles_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_people_warm_threshold_days
-- Field: People.WarmThresholdDays
-- Type: lookup | DataType: integer | Returns: INTEGER
-- Lookup: WarmThresholdDays from related Profiles


CREATE OR REPLACE FUNCTION calc_people_warm_threshold_days(p_people_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT warm_threshold_days::integer FROM profiles WHERE profiles_id = (SELECT owner FROM people WHERE people_id = p_people_id));
$$ LANGUAGE sql STABLE;

-- calc_people_cooling_threshold_days
-- Field: People.CoolingThresholdDays
-- Type: lookup | DataType: integer | Returns: INTEGER
-- Lookup: CoolingThresholdDays from related Profiles


CREATE OR REPLACE FUNCTION calc_people_cooling_threshold_days(p_people_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT cooling_threshold_days::integer FROM profiles WHERE profiles_id = (SELECT owner FROM people WHERE people_id = p_people_id));
$$ LANGUAGE sql STABLE;

-- get_profiles_account_key
-- Helper function: Get AccountKey from Profiles by ProfilesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_profiles_account_key(p_profiles_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT account_key FROM profiles WHERE profiles_id = p_profiles_id);
$$ LANGUAGE sql STABLE;

-- get_profiles_display_name
-- Helper function: Get DisplayName from Profiles by ProfilesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_profiles_display_name(p_profiles_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT display_name FROM profiles WHERE profiles_id = p_profiles_id);
$$ LANGUAGE sql STABLE;

-- get_profiles_tagline
-- Helper function: Get Tagline from Profiles by ProfilesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_profiles_tagline(p_profiles_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT tagline FROM profiles WHERE profiles_id = p_profiles_id);
$$ LANGUAGE sql STABLE;

-- get_profiles_weekly_warmup_goal
-- Helper function: Get WeeklyWarmupGoal from Profiles by ProfilesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_profiles_weekly_warmup_goal(p_profiles_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT weekly_warmup_goal FROM profiles WHERE profiles_id = p_profiles_id);
$$ LANGUAGE sql STABLE;

-- get_profiles_warm_threshold_days
-- Helper function: Get WarmThresholdDays from Profiles by ProfilesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_profiles_warm_threshold_days(p_profiles_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT warm_threshold_days FROM profiles WHERE profiles_id = p_profiles_id);
$$ LANGUAGE sql STABLE;

-- get_profiles_cooling_threshold_days
-- Helper function: Get CoolingThresholdDays from Profiles by ProfilesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_profiles_cooling_threshold_days(p_profiles_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT cooling_threshold_days FROM profiles WHERE profiles_id = p_profiles_id);
$$ LANGUAGE sql STABLE;

-- get_profiles_morning_warmup_count
-- Helper function: Get MorningWarmupCount from Profiles by ProfilesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_profiles_morning_warmup_count(p_profiles_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT morning_warmup_count FROM profiles WHERE profiles_id = p_profiles_id);
$$ LANGUAGE sql STABLE;

-- get_profiles_week_start
-- Helper function: Get WeekStart from Profiles by ProfilesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_profiles_week_start(p_profiles_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT week_start FROM profiles WHERE profiles_id = p_profiles_id);
$$ LANGUAGE sql STABLE;

-- get_profiles_week_count
-- Helper function: Get WeekCount from Profiles by ProfilesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_profiles_week_count(p_profiles_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT week_count FROM profiles WHERE profiles_id = p_profiles_id);
$$ LANGUAGE sql STABLE;

-- get_spheres_sphere_label
-- Helper function: Get SphereLabel from Spheres by SpheresId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_spheres_sphere_label(p_spheres_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT sphere_label FROM spheres WHERE spheres_id = p_spheres_id);
$$ LANGUAGE sql STABLE;

-- get_spheres_description
-- Helper function: Get Description from Spheres by SpheresId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_spheres_description(p_spheres_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM spheres WHERE spheres_id = p_spheres_id);
$$ LANGUAGE sql STABLE;

-- get_spheres_sort_order
-- Helper function: Get SortOrder from Spheres by SpheresId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_spheres_sort_order(p_spheres_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM spheres WHERE spheres_id = p_spheres_id);
$$ LANGUAGE sql STABLE;

-- get_person_statuses_status_label
-- Helper function: Get StatusLabel from PersonStatuses by PersonStatusesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_person_statuses_status_label(p_person_statuses_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT status_label FROM person_statuses WHERE person_statuses_id = p_person_statuses_id);
$$ LANGUAGE sql STABLE;

-- get_person_statuses_description
-- Helper function: Get Description from PersonStatuses by PersonStatusesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_person_statuses_description(p_person_statuses_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM person_statuses WHERE person_statuses_id = p_person_statuses_id);
$$ LANGUAGE sql STABLE;

-- get_person_statuses_sort_order
-- Helper function: Get SortOrder from PersonStatuses by PersonStatusesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_person_statuses_sort_order(p_person_statuses_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM person_statuses WHERE person_statuses_id = p_person_statuses_id);
$$ LANGUAGE sql STABLE;

-- calc_people_name
-- Field: People.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_people_name(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(full_name, '') FROM people WHERE people_id = p_people_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_people_days_since_last_touched
-- Field: People.DaysSinceLastTouched
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_people_days_since_last_touched(p_people_id TEXT)
RETURNS INTEGER AS $$
  SELECT /* WARNING: Formula translation failed: Function 'ISBLANK' is not supported yet
   Original Airtable formula:
   =IF(ISBLANK({{LastTouched}}), 0, TODAY() - {{LastTouched}})
*/
NULL::integer;
$$ LANGUAGE sql STABLE;

-- calc_people_is_never_touched
-- Field: People.IsNeverTouched
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_people_is_never_touched(p_people_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT /* WARNING: Formula translation failed: Function 'ISBLANK' is not supported yet
   Original Airtable formula:
   =IF(ISBLANK({{LastTouched}}), TRUE(), FALSE())
*/
NULL::boolean;
$$ LANGUAGE sql STABLE;

-- calc_people_warmth
-- Field: People.Warmth
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_people_warmth(p_people_id TEXT)
RETURNS TEXT AS $$
  SELECT /* WARNING: Formula translation failed: Function 'ISBLANK' is not supported yet
   Original Airtable formula:
   =IF(ISBLANK({{LastTouched}}), "cold", IF({{DaysSinceLastTouched}} <= {{WarmThresholdDays}}, "warm", IF({{DaysSinceLastTouched}} <= {{CoolingThresholdDays}}, "cooling", "cold")))
*/
NULL::text;
$$ LANGUAGE sql STABLE;

-- calc_facilities_region_label
-- Field: Facilities.RegionLabel
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: RegionLabel from related Regions


CREATE OR REPLACE FUNCTION calc_facilities_region_label(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT region_label::text FROM regions WHERE regions_id = (SELECT region FROM facilities WHERE facilities_id = p_facilities_id));
$$ LANGUAGE sql STABLE;

-- calc_facilities_lead_route_label
-- Field: Facilities.LeadRouteLabel
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: LeadRouteLabel from related LeadRoutes


CREATE OR REPLACE FUNCTION calc_facilities_lead_route_label(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT lead_route_label::text FROM lead_routes WHERE lead_routes_id = (SELECT lead_route FROM facilities WHERE facilities_id = p_facilities_id));
$$ LANGUAGE sql STABLE;

-- get_facility_types_type_label
-- Helper function: Get TypeLabel from FacilityTypes by FacilityTypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facility_types_type_label(p_facility_types_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT type_label FROM facility_types WHERE facility_types_id = p_facility_types_id);
$$ LANGUAGE sql STABLE;

-- get_facility_types_description
-- Helper function: Get Description from FacilityTypes by FacilityTypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facility_types_description(p_facility_types_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM facility_types WHERE facility_types_id = p_facility_types_id);
$$ LANGUAGE sql STABLE;

-- get_facility_types_sort_order
-- Helper function: Get SortOrder from FacilityTypes by FacilityTypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facility_types_sort_order(p_facility_types_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM facility_types WHERE facility_types_id = p_facility_types_id);
$$ LANGUAGE sql STABLE;

-- get_regions_region_label
-- Helper function: Get RegionLabel from Regions by RegionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_regions_region_label(p_regions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT region_label FROM regions WHERE regions_id = p_regions_id);
$$ LANGUAGE sql STABLE;

-- get_regions_description
-- Helper function: Get Description from Regions by RegionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_regions_description(p_regions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM regions WHERE regions_id = p_regions_id);
$$ LANGUAGE sql STABLE;

-- get_regions_sort_order
-- Helper function: Get SortOrder from Regions by RegionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_regions_sort_order(p_regions_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM regions WHERE regions_id = p_regions_id);
$$ LANGUAGE sql STABLE;

-- get_lead_routes_lead_route_label
-- Helper function: Get LeadRouteLabel from LeadRoutes by LeadRoutesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_lead_routes_lead_route_label(p_lead_routes_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT lead_route_label FROM lead_routes WHERE lead_routes_id = p_lead_routes_id);
$$ LANGUAGE sql STABLE;

-- get_lead_routes_description
-- Helper function: Get Description from LeadRoutes by LeadRoutesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_lead_routes_description(p_lead_routes_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM lead_routes WHERE lead_routes_id = p_lead_routes_id);
$$ LANGUAGE sql STABLE;

-- get_lead_routes_sort_order
-- Helper function: Get SortOrder from LeadRoutes by LeadRoutesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_lead_routes_sort_order(p_lead_routes_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM lead_routes WHERE lead_routes_id = p_lead_routes_id);
$$ LANGUAGE sql STABLE;

-- get_alignment_levels_alignment_label
-- Helper function: Get AlignmentLabel from AlignmentLevels by AlignmentLevelsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_alignment_levels_alignment_label(p_alignment_levels_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT alignment_label FROM alignment_levels WHERE alignment_levels_id = p_alignment_levels_id);
$$ LANGUAGE sql STABLE;

-- get_alignment_levels_description
-- Helper function: Get Description from AlignmentLevels by AlignmentLevelsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_alignment_levels_description(p_alignment_levels_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM alignment_levels WHERE alignment_levels_id = p_alignment_levels_id);
$$ LANGUAGE sql STABLE;

-- get_alignment_levels_sort_order
-- Helper function: Get SortOrder from AlignmentLevels by AlignmentLevelsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_alignment_levels_sort_order(p_alignment_levels_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM alignment_levels WHERE alignment_levels_id = p_alignment_levels_id);
$$ LANGUAGE sql STABLE;

-- get_facility_statuses_status_label
-- Helper function: Get StatusLabel from FacilityStatuses by FacilityStatusesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facility_statuses_status_label(p_facility_statuses_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT status_label FROM facility_statuses WHERE facility_statuses_id = p_facility_statuses_id);
$$ LANGUAGE sql STABLE;

-- get_facility_statuses_description
-- Helper function: Get Description from FacilityStatuses by FacilityStatusesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facility_statuses_description(p_facility_statuses_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM facility_statuses WHERE facility_statuses_id = p_facility_statuses_id);
$$ LANGUAGE sql STABLE;

-- get_facility_statuses_sort_order
-- Helper function: Get SortOrder from FacilityStatuses by FacilityStatusesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_facility_statuses_sort_order(p_facility_statuses_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM facility_statuses WHERE facility_statuses_id = p_facility_statuses_id);
$$ LANGUAGE sql STABLE;

-- calc_facilities_name
-- Field: Facilities.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_facilities_name(p_facilities_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(facility_name, '') FROM facilities WHERE facilities_id = p_facilities_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_facilities_is_warm_lead
-- Field: Facilities.IsWarmLead
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_facilities_is_warm_lead(p_facilities_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN ((SELECT NULLIF(lead_route, '') FROM facilities WHERE facilities_id = p_facilities_id) = 'warm-via-mina' OR (SELECT NULLIF(lead_route, '') FROM facilities WHERE facilities_id = p_facilities_id) = 'warm-via-haley' OR (SELECT NULLIF(lead_route, '') FROM facilities WHERE facilities_id = p_facilities_id) = 'warm-via-other') THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- get_capture_types_type_label
-- Helper function: Get TypeLabel from CaptureTypes by CaptureTypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_capture_types_type_label(p_capture_types_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT type_label FROM capture_types WHERE capture_types_id = p_capture_types_id);
$$ LANGUAGE sql STABLE;

-- get_capture_types_description
-- Helper function: Get Description from CaptureTypes by CaptureTypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_capture_types_description(p_capture_types_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM capture_types WHERE capture_types_id = p_capture_types_id);
$$ LANGUAGE sql STABLE;

-- get_capture_types_sort_order
-- Helper function: Get SortOrder from CaptureTypes by CaptureTypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_capture_types_sort_order(p_capture_types_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM capture_types WHERE capture_types_id = p_capture_types_id);
$$ LANGUAGE sql STABLE;

-- calc_captures_name
-- Field: Captures.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_captures_name(p_captures_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(title, '') FROM captures WHERE captures_id = p_captures_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_o_auth_tokens_name
-- Field: OAuthTokens.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_o_auth_tokens_name(p_o_auth_tokens_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(owner, '') FROM o_auth_tokens WHERE o_auth_tokens_id = p_o_auth_tokens_id), '-', (SELECT NULLIF(provider, '') FROM o_auth_tokens WHERE o_auth_tokens_id = p_o_auth_tokens_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_spheres_name
-- Field: Spheres.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_spheres_name(p_spheres_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(sphere_label, '') FROM spheres WHERE spheres_id = p_spheres_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_spheres_count_of_people
-- Field: Spheres.CountOfPeople
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_spheres_count_of_people(p_spheres_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM people WHERE sphere = calc_spheres_name(p_spheres_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_person_statuses_name
-- Field: PersonStatuses.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_person_statuses_name(p_person_statuses_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(status_label, '') FROM person_statuses WHERE person_statuses_id = p_person_statuses_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_person_statuses_count_of_people
-- Field: PersonStatuses.CountOfPeople
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_person_statuses_count_of_people(p_person_statuses_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM people WHERE status = calc_person_statuses_name(p_person_statuses_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_facility_types_name
-- Field: FacilityTypes.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_facility_types_name(p_facility_types_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(type_label, '') FROM facility_types WHERE facility_types_id = p_facility_types_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_facility_types_count_of_facilities
-- Field: FacilityTypes.CountOfFacilities
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_facility_types_count_of_facilities(p_facility_types_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM facilities WHERE type = calc_facility_types_name(p_facility_types_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_regions_name
-- Field: Regions.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_regions_name(p_regions_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(region_label, '') FROM regions WHERE regions_id = p_regions_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_regions_count_of_facilities
-- Field: Regions.CountOfFacilities
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_regions_count_of_facilities(p_regions_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM facilities WHERE region = calc_regions_name(p_regions_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_lead_routes_name
-- Field: LeadRoutes.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_lead_routes_name(p_lead_routes_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(lead_route_label, '') FROM lead_routes WHERE lead_routes_id = p_lead_routes_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_lead_routes_count_of_facilities
-- Field: LeadRoutes.CountOfFacilities
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_lead_routes_count_of_facilities(p_lead_routes_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM facilities WHERE lead_route = calc_lead_routes_name(p_lead_routes_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_alignment_levels_name
-- Field: AlignmentLevels.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_alignment_levels_name(p_alignment_levels_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(alignment_label, '') FROM alignment_levels WHERE alignment_levels_id = p_alignment_levels_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_alignment_levels_count_of_facilities
-- Field: AlignmentLevels.CountOfFacilities
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_alignment_levels_count_of_facilities(p_alignment_levels_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM facilities WHERE aligned = calc_alignment_levels_name(p_alignment_levels_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_facility_statuses_name
-- Field: FacilityStatuses.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_facility_statuses_name(p_facility_statuses_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(status_label, '') FROM facility_statuses WHERE facility_statuses_id = p_facility_statuses_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_facility_statuses_count_of_facilities
-- Field: FacilityStatuses.CountOfFacilities
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_facility_statuses_count_of_facilities(p_facility_statuses_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM facilities WHERE status = calc_facility_statuses_name(p_facility_statuses_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_capture_types_name
-- Field: CaptureTypes.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_capture_types_name(p_capture_types_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(type_label, '') FROM capture_types WHERE capture_types_id = p_capture_types_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_capture_types_count_of_captures
-- Field: CaptureTypes.CountOfCaptures
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_capture_types_count_of_captures(p_capture_types_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM captures WHERE type = calc_capture_types_name(p_capture_types_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_warmth_levels_name
-- Field: WarmthLevels.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_warmth_levels_name(p_warmth_levels_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(warmth_label, '') FROM warmth_levels WHERE warmth_levels_id = p_warmth_levels_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_governance_rules_name
-- Field: GovernanceRules.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_governance_rules_name(p_governance_rules_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(title, '') FROM governance_rules WHERE governance_rules_id = p_governance_rules_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

