-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Views: 15
-- ============================================================================

-- ----------------------------------------------------------------------------
-- vw_profiles: Per-user settings, one row per user. Holds the gentle parameters that drive the daily ritual. This is the ownership root: every owned row points back here through its Owner relationship.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_profiles WITH (security_invoker = ON) AS
SELECT
  t.profiles_id,                                                                -- Primary key (auto-synthesized: Profiles had no field named 'Id' or ending in 'Id').
  calc_profiles_name(t.profiles_id) AS name,                                    -- Logical key for the profile, a slug of the account key. Maps to the per-user identity in the substrate.
  t.account_key,                                                                -- Stable per-user identity key. Maps to user_id in the generated schema. Owned rows reference this value through their Owner relationship.
  t.display_name,                                                               -- Friendly display name shown in the app. Default Liz. Maps to profile.display_name.
  t.tagline,                                                                    -- Personal tagline. Default Illuminating Life, Legacy, and Love. Maps to profile.tagline.
  t.weekly_warmup_goal,                                                         -- Target number of hellos per week, shown as encouragement, never a backlog. Default 4. Maps to profile.weekly_warmup_goal. See GovernanceRules R4.
  t.warm_threshold_days,                                                        -- A person stays Warm within this many days of the last hello. Default 14. Maps to profile.warm_threshold_days. See GovernanceRules R2.
  t.cooling_threshold_days,                                                     -- A person is Cooling up to this many days since the last hello, then Cold beyond it. Default 30. Maps to profile.cooling_threshold_days. See GovernanceRules R2.
  t.morning_warmup_count,                                                       -- How many people the Today screen surfaces each morning, one at a time. Default 3. Maps to profile.morning_warmup_count. See GovernanceRules R3.
  t.week_start,                                                                 -- Anchor for the weekly count, set to the most recent Monday. Maps to profile.week_start. See GovernanceRules R4.
  t.week_count,                                                                 -- Hellos logged since WeekStart, maintained by the app and reset each Monday. Default 0. Maps to profile.week_count.
  t.people,                                                                     -- The people owned by this profile.
  t.facilities,                                                                 -- The facilities owned by this profile.
  t.captures,                                                                   -- The captures owned by this profile.
  t.o_auth_tokens,                                                              -- The server-side OAuth tokens owned by this profile.
  calc_profiles_count_of_people(t.profiles_id) AS count_of_people,              -- Number of people in this profile's warm network.
  calc_profiles_count_of_facilities(t.profiles_id) AS count_of_facilities,      -- Number of target facilities owned by this profile.
  calc_profiles_count_of_captures(t.profiles_id) AS count_of_captures           -- Number of captures owned by this profile.
FROM profiles t;

-- ----------------------------------------------------------------------------
-- vw_people: The warm network. Liz's sphere of influence and community ecosystem, anyone who can open a door or help map who is aligned.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_people WITH (security_invoker = ON) AS
SELECT
  t.people_id,                                                                  -- Primary key (auto-synthesized: People had no field named 'Id' or ending in 'Id').
  calc_people_name(t.people_id) AS name,                                        -- Logical key for the person, a slug of FullName.
  t.full_name,                                                                  -- The person's name. The only required field on a person. Maps to people.name. See GovernanceRules R6.
  t.owner,                                                                      -- The profile that owns this row. Holds the Profiles Name. Drives Row Level Security. Maps to people.user_id. See GovernanceRules R1.
  t.role_org,                                                                   -- The person's role or organization. Maps to people.role_org.
  t.sphere,                                                                     -- Which sphere of the network this person belongs to. Holds the Spheres Name. Maps to people.sphere.
  t.relationship,                                                               -- How Liz knows this person, in her own words. Maps to people.relationship.
  t.doors_can_open,                                                             -- What doors this person can open or who they can introduce. Maps to people.doors_can_open.
  t.the_ask,                                                                    -- The specific ask or next favor, kept human and light. Maps to people.the_ask.
  t.email,                                                                      -- Email address, used by the native email compose link. Maps to people.email.
  t.phone,                                                                      -- Phone number. Maps to people.phone.
  t.linkedin_url,                                                               -- LinkedIn profile URL, used only for Open in LinkedIn deep links. Maps to people.linkedin_url. See GovernanceRules R10.
  t.status,                                                                     -- Where this relationship stands. Holds the PersonStatuses Name. Defaults to to-reach-out. Maps to people.status.
  t.last_touched,                                                               -- Date of the most recent hello. Logging a hello sets this to today. Drives Warmth. Maps to people.last_touched. See GovernanceRules R2 and R3.
  t.next_step,                                                                  -- The gentle next step with this person. Maps to people.next_step.
  t.notes,                                                                      -- Free notes. Maps to people.notes.
  calc_people_warm_threshold_days(t.people_id) AS warm_threshold_days,          -- The owner's warm threshold in days, pulled from the owning profile. Falls back to 14 when the profile leaves it blank, so a missing threshold never silently turns every contact cold.
  calc_people_cooling_threshold_days(t.people_id) AS cooling_threshold_days,    -- The owner's cooling threshold in days, pulled from the owning profile. Falls back to 30 when the profile leaves it blank.
  calc_people_days_since_last_touched(t.people_id) AS days_since_last_touched,  -- Days since the last hello, or 0 when never touched. Time relative, resolved at view-compute time. ISBLANK guards the unset (NULL) date.
  calc_people_is_never_touched(t.people_id) AS is_never_touched,                -- True when there is no recorded hello yet. A never touched contact reads as ready for a hello, never as overdue. See GovernanceRules R5.
  calc_people_warmth(t.people_id) AS warmth                                     -- Derived warmth: warm within WarmThresholdDays, cooling up to CoolingThresholdDays, otherwise cold, including never touched. Matches a WarmthLevels Name. Drives sorting and the daily ritual only. See GovernanceRules R2.
FROM people t;

-- ----------------------------------------------------------------------------
-- vw_facilities: The target places. Values aligned independent living and 55 and over communities first, the places Liz is working toward.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_facilities WITH (security_invoker = ON) AS
SELECT
  t.facilities_id,                                                              -- Primary key (auto-synthesized: Facilities had no field named 'Id' or ending in 'Id').
  calc_facilities_name(t.facilities_id) AS name,                                -- Logical key for the facility, a slug of FacilityName.
  t.facility_name,                                                              -- The facility name. The only required field on a facility. Maps to facilities.facility_name. See GovernanceRules R6.
  t.owner,                                                                      -- The profile that owns this row. Holds the Profiles Name. Drives Row Level Security. Maps to facilities.user_id. See GovernanceRules R1.
  t.type,                                                                       -- The kind of facility. Holds the FacilityTypes Name. Maps to facilities.type.
  t.town,                                                                       -- Town where the facility is located. Maps to facilities.town.
  t.region,                                                                     -- Region grouping for the facility. Holds the Regions Name. Maps to facilities.region.
  t.lead_route,                                                                 -- How Liz can reach this facility, warm or cold. Holds the LeadRoutes Name. Maps to facilities.lead_route.
  t.aligned,                                                                    -- Whether the facility seems values aligned. Holds the AlignmentLevels Name. Maps to facilities.aligned.
  t.decision_maker,                                                             -- Name of the person who decides. Maps to facilities.decision_maker.
  t.title,                                                                      -- Title of the decision maker. Maps to facilities.title.
  t.email,                                                                      -- Contact email. Maps to facilities.email.
  t.phone,                                                                      -- Contact phone. Maps to facilities.phone.
  t.website,                                                                    -- Facility website. Maps to facilities.website.
  t.status,                                                                     -- Where the outreach stands. Holds the FacilityStatuses Name. Defaults to to-research. Maps to facilities.status.
  t.next_step,                                                                  -- The gentle next step with this facility. Maps to facilities.next_step.
  t.fit_notes,                                                                  -- Notes on fit and alignment. Maps to facilities.fit_notes.
  calc_facilities_region_label(t.facilities_id) AS region_label,                -- Human readable region label, pulled from the related region.
  calc_facilities_lead_route_label(t.facilities_id) AS lead_route_label,        -- Human readable lead route label, pulled from the related lead route.
  calc_facilities_is_warm_lead(t.facilities_id) AS is_warm_lead                 -- True when there is a warm route into this facility rather than a cold approach.
FROM facilities t;

-- ----------------------------------------------------------------------------
-- vw_captures: Pain points, case studies, and ideas, captured as they come. Feeds the marketing package.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_captures WITH (security_invoker = ON) AS
SELECT
  t.captures_id,                                                                -- Primary key (auto-synthesized: Captures had no field named 'Id' or ending in 'Id').
  calc_captures_name(t.captures_id) AS name,                                    -- Logical key for the capture, a slug of Title.
  t.title,                                                                      -- Short title of the capture. The only required field on a capture. Maps to captures.title. See GovernanceRules R6.
  t.owner,                                                                      -- The profile that owns this row. Holds the Profiles Name. Drives Row Level Security. Maps to captures.user_id. See GovernanceRules R1.
  t.type,                                                                       -- The kind of capture. Holds the CaptureTypes Name. Defaults to idea. Maps to captures.type.
  t.detail                                                                      -- The full text of the capture. Maps to captures.detail.
FROM captures t;

-- ----------------------------------------------------------------------------
-- vw_o_auth_tokens: Server-side storage for Drive, LinkedIn, and optional Calendar and Gmail tokens. Never exposed to the client. Read and refreshed only in server code. See GovernanceRules R12.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_o_auth_tokens WITH (security_invoker = ON) AS
SELECT
  t.o_auth_tokens_id,                                                           -- Primary key (auto-synthesized: OAuthTokens had no field named 'Id' or ending in 'Id').
  calc_o_auth_tokens_name(t.o_auth_tokens_id) AS name,                          -- Logical key for the token, a compound of owner and provider.
  t.owner,                                                                      -- The profile that owns this token. Holds the Profiles Name. Maps to oauth_tokens.user_id. See GovernanceRules R1.
  t.provider,                                                                   -- The integration this token is for, for example google-drive, linkedin, google-calendar, or gmail. Maps to oauth_tokens.provider.
  t.access_token,                                                               -- Short lived access token. Server-side only, never sent to the client. Maps to oauth_tokens.access_token. See GovernanceRules R12.
  t.refresh_token,                                                              -- Long lived refresh token, stored encrypted and tied to the owner. Server-side only. Maps to oauth_tokens.refresh_token. See GovernanceRules R12.
  t.scope,                                                                      -- The granted OAuth scope, kept as narrow as the feature needs. Maps to oauth_tokens.scope. See GovernanceRules R11.
  t.expires_at                                                                  -- When the access token expires. Maps to oauth_tokens.expires_at.
FROM o_auth_tokens t;

-- ----------------------------------------------------------------------------
-- vw_spheres: Controlled vocabulary for people.sphere. The part of the network a person belongs to. Generated as a derivative enum table. Do not hardcode these in the frontend or schema.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_spheres WITH (security_invoker = ON) AS
SELECT
  t.spheres_id,                                                                 -- Primary key (auto-synthesized: Spheres had no field named 'Id' or ending in 'Id').
  calc_spheres_name(t.spheres_id) AS name,                                      -- Slug key for the sphere, derived from the label.
  t.sphere_label,                                                               -- Human readable sphere label shown in the app.
  t.description,                                                                -- What this sphere means.
  t.sort_order,                                                                 -- Display order in pickers.
  t.people,                                                                     -- People in this sphere.
  calc_spheres_count_of_people(t.spheres_id) AS count_of_people                 -- Number of people in this sphere.
FROM spheres t;

-- ----------------------------------------------------------------------------
-- vw_person_statuses: Controlled vocabulary for people.status. Where a relationship stands. Generated as a derivative enum table.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_person_statuses WITH (security_invoker = ON) AS
SELECT
  t.person_statuses_id,                                                         -- Primary key (auto-synthesized: PersonStatuses had no field named 'Id' or ending in 'Id').
  calc_person_statuses_name(t.person_statuses_id) AS name,                      -- Slug key for the status, derived from the label.
  t.status_label,                                                               -- Human readable status label shown in the app.
  t.description,                                                                -- What this status means.
  t.sort_order,                                                                 -- Display order in pickers.
  t.people,                                                                     -- People at this status.
  calc_person_statuses_count_of_people(t.person_statuses_id) AS count_of_people -- Number of people at this status.
FROM person_statuses t;

-- ----------------------------------------------------------------------------
-- vw_facility_types: Controlled vocabulary for facilities.type. The kind of place. Generated as a derivative enum table.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_facility_types WITH (security_invoker = ON) AS
SELECT
  t.facility_types_id,                                                          -- Primary key (auto-synthesized: FacilityTypes had no field named 'Id' or ending in 'Id').
  calc_facility_types_name(t.facility_types_id) AS name,                        -- Slug key for the facility type, derived from the label.
  t.type_label,                                                                 -- Human readable facility type label shown in the app.
  t.description,                                                                -- What this facility type means.
  t.sort_order,                                                                 -- Display order in pickers.
  t.facilities,                                                                 -- Facilities of this type.
  calc_facility_types_count_of_facilities(t.facility_types_id) AS count_of_facilities-- Number of facilities of this type.
FROM facility_types t;

-- ----------------------------------------------------------------------------
-- vw_regions: Controlled vocabulary for facilities.region. Geographic grouping. Generated as a derivative enum table.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_regions WITH (security_invoker = ON) AS
SELECT
  t.regions_id,                                                                 -- Primary key (auto-synthesized: Regions had no field named 'Id' or ending in 'Id').
  calc_regions_name(t.regions_id) AS name,                                      -- Slug key for the region, derived from the label.
  t.region_label,                                                               -- Human readable region label shown in the app.
  t.description,                                                                -- What this region covers.
  t.sort_order,                                                                 -- Display order in pickers.
  t.facilities,                                                                 -- Facilities in this region.
  calc_regions_count_of_facilities(t.regions_id) AS count_of_facilities         -- Number of facilities in this region.
FROM regions t;

-- ----------------------------------------------------------------------------
-- vw_lead_routes: Controlled vocabulary for facilities.lead_route. How Liz can reach a facility. Generated as a derivative enum table.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_lead_routes WITH (security_invoker = ON) AS
SELECT
  t.lead_routes_id,                                                             -- Primary key (auto-synthesized: LeadRoutes had no field named 'Id' or ending in 'Id').
  calc_lead_routes_name(t.lead_routes_id) AS name,                              -- Slug key for the lead route, derived from the label.
  t.lead_route_label,                                                           -- Human readable lead route label shown in the app.
  t.description,                                                                -- What this lead route means.
  t.sort_order,                                                                 -- Display order in pickers.
  t.facilities,                                                                 -- Facilities reached through this route.
  calc_lead_routes_count_of_facilities(t.lead_routes_id) AS count_of_facilities -- Number of facilities reached through this route.
FROM lead_routes t;

-- ----------------------------------------------------------------------------
-- vw_alignment_levels: Controlled vocabulary for facilities.aligned. Whether a facility seems values aligned. Generated as a derivative enum table.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_alignment_levels WITH (security_invoker = ON) AS
SELECT
  t.alignment_levels_id,                                                        -- Primary key (auto-synthesized: AlignmentLevels had no field named 'Id' or ending in 'Id').
  calc_alignment_levels_name(t.alignment_levels_id) AS name,                    -- Slug key for the alignment level, derived from the label.
  t.alignment_label,                                                            -- Human readable alignment label shown in the app.
  t.description,                                                                -- What this alignment level means.
  t.sort_order,                                                                 -- Display order in pickers.
  t.facilities,                                                                 -- Facilities at this alignment level.
  calc_alignment_levels_count_of_facilities(t.alignment_levels_id) AS count_of_facilities-- Number of facilities at this alignment level.
FROM alignment_levels t;

-- ----------------------------------------------------------------------------
-- vw_facility_statuses: Controlled vocabulary for facilities.status. Where the outreach stands. Generated as a derivative enum table.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_facility_statuses WITH (security_invoker = ON) AS
SELECT
  t.facility_statuses_id,                                                       -- Primary key (auto-synthesized: FacilityStatuses had no field named 'Id' or ending in 'Id').
  calc_facility_statuses_name(t.facility_statuses_id) AS name,                  -- Slug key for the facility status, derived from the label.
  t.status_label,                                                               -- Human readable facility status label shown in the app.
  t.description,                                                                -- What this facility status means.
  t.sort_order,                                                                 -- Display order in pickers.
  t.facilities,                                                                 -- Facilities at this status.
  calc_facility_statuses_count_of_facilities(t.facility_statuses_id) AS count_of_facilities-- Number of facilities at this status.
FROM facility_statuses t;

-- ----------------------------------------------------------------------------
-- vw_capture_types: Controlled vocabulary for captures.type. The kind of capture. Generated as a derivative enum table.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_capture_types WITH (security_invoker = ON) AS
SELECT
  t.capture_types_id,                                                           -- Primary key (auto-synthesized: CaptureTypes had no field named 'Id' or ending in 'Id').
  calc_capture_types_name(t.capture_types_id) AS name,                          -- Slug key for the capture type, derived from the label.
  t.type_label,                                                                 -- Human readable capture type label shown in the app.
  t.description,                                                                -- What this capture type means.
  t.sort_order,                                                                 -- Display order in pickers.
  t.captures,                                                                   -- Captures of this type.
  calc_capture_types_count_of_captures(t.capture_types_id) AS count_of_captures -- Number of captures of this type.
FROM capture_types t;

-- ----------------------------------------------------------------------------
-- vw_warmth_levels: Controlled vocabulary for the derived warmth value. Warmth is computed from LastTouched and is not stored. These rows give the frontend the labels and gentle framing for each level. See GovernanceRules R2 and R5.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_warmth_levels WITH (security_invoker = ON) AS
SELECT
  t.warmth_levels_id,                                                           -- Primary key (auto-synthesized: WarmthLevels had no field named 'Id' or ending in 'Id').
  calc_warmth_levels_name(t.warmth_levels_id) AS name,                          -- Slug key for the warmth level, derived from the label. Matches the value returned by People.Warmth.
  t.warmth_label,                                                               -- Human readable warmth label shown in the app.
  t.description,                                                                -- What this warmth level means.
  t.guidance,                                                                   -- Gentle framing shown to Liz. No guilt, a cold contact reads as ready for a hello. See GovernanceRules R5.
  t.sort_order                                                                  -- Display order, warmest first.
FROM warmth_levels t;

-- ----------------------------------------------------------------------------
-- vw_governance_rules: The governance rules for the BeaconHaus Companion, one row per rule. Each rule is meaning that lives in the rulebook and is traceable. The frontend and backend enforce these because they are generated from them, not because someone wrote them into code by hand.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_governance_rules WITH (security_invoker = ON) AS
SELECT
  t.governance_rules_id,                                                        -- Primary key (auto-synthesized: GovernanceRules had no field named 'Id' or ending in 'Id').
  calc_governance_rules_name(t.governance_rules_id) AS name,                    -- Slug key for the rule, derived from the title.
  t.rule_code,                                                                  -- Short rule code, R1 through R12.
  t.title,                                                                      -- Short title of the rule.
  t.statement,                                                                  -- The full rule statement, the meaning that downstream artifacts must honor.
  t.category,                                                                   -- Grouping for the rule, for example Ownership, Warmth, Ritual, Content, Positioning, Integration, Security, or UX.
  t.enforced_by,                                                                -- Where this rule is realized in the derivative outputs.
  t.sort_order                                                                  -- Display order, R1 through R12.
FROM governance_rules t;

