-- ============================================================================
-- CREATE POLICIES - Row Level Security policies
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================

-- Enable RLS on all tables

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE people ENABLE ROW LEVEL SECURITY;
ALTER TABLE facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE captures ENABLE ROW LEVEL SECURITY;
ALTER TABLE o_auth_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE spheres ENABLE ROW LEVEL SECURITY;
ALTER TABLE person_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE facility_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE regions ENABLE ROW LEVEL SECURITY;
ALTER TABLE lead_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE alignment_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE facility_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE capture_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE warmth_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE governance_rules ENABLE ROW LEVEL SECURITY;

-- TODO: Add specific RLS policies based on your security requirements
-- Example:
-- CREATE POLICY "Users can view their own data" ON app_user
--   FOR SELECT USING (auth.uid() = user_id);

