-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Profiles: Per-user settings, one row per user. Holds the gentle parameters that drive the daily ritual. This is the ownership root: every owned row points back here through its Owner relationship.
-- ----------------------------------------------------------------------------
INSERT INTO profiles (profiles_id, account_key, display_name, tagline, weekly_warmup_goal, warm_threshold_days, cooling_threshold_days, morning_warmup_count, week_start, week_count, people, facilities, captures, o_auth_tokens)
VALUES ('ea79adae-0ca6-c1dd-c0f6-b6c76f690c32', 'liz', 'Liz', 'Illuminating Life, Legacy, and Love', 4, 14, 30, 3, NULL, 0, NULL, NULL, NULL, NULL) ON CONFLICT (profiles_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- People: The warm network. Liz's sphere of influence and community ecosystem, anyone who can open a door or help map who is aligned.
-- ----------------------------------------------------------------------------
INSERT INTO people (people_id, full_name, owner, role_org, sphere, relationship, doors_can_open, the_ask, email, phone, linkedin_url, status, last_touched, next_step, notes)
VALUES ('b077449e-e001-d200-06a9-362b38a938c0', 'Mina', 'liz', 'Warm connector into local facilities', 'facility', 'Trusted connector who can make warm introductions', 'Introductions to the Warwick and Goshen facility targets', 'Confirm the two unconfirmed Warwick and Goshen facility names and offer a warm intro', NULL, NULL, NULL, 'in-conversation', NULL, 'Sit down with Mina to confirm targets', 'Primary warm route for facility outreach.') ON CONFLICT (people_id) DO NOTHING;

INSERT INTO people (people_id, full_name, owner, role_org, sphere, relationship, doors_can_open, the_ask, email, phone, linkedin_url, status, last_touched, next_step, notes)
VALUES ('b9dbe929-2ed4-4390-5352-0cb13d6a356b', 'Haley', 'liz', 'Community connector', 'community', 'Connector who can make warm introductions', 'Warm introductions within the community ecosystem', NULL, NULL, NULL, NULL, 'in-conversation', NULL, 'Check in and thank Haley for recent introductions', 'Secondary warm route.') ON CONFLICT (people_id) DO NOTHING;

INSERT INTO people (people_id, full_name, owner, role_org, sphere, relationship, doors_can_open, the_ask, email, phone, linkedin_url, status, last_touched, next_step, notes)
VALUES ('20bb2060-6ea4-d340-8fce-72f80a9ed664', 'Pam', 'liz', NULL, 'community', NULL, NULL, NULL, NULL, NULL, NULL, 'reached-out', NULL, 'Follow up on the last conversation', 'Curated starter contact, details to be confirmed with Liz.') ON CONFLICT (people_id) DO NOTHING;

INSERT INTO people (people_id, full_name, owner, role_org, sphere, relationship, doors_can_open, the_ask, email, phone, linkedin_url, status, last_touched, next_step, notes)
VALUES ('2b5087f2-1ec9-90c7-c058-f963ef903343', 'Terry', 'liz', NULL, 'community', NULL, NULL, NULL, NULL, NULL, NULL, 'to-reach-out', NULL, 'Send a first warm hello', 'Curated starter contact, details to be confirmed with Liz.') ON CONFLICT (people_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Facilities: The target places. Values aligned independent living and 55 and over communities first, the places Liz is working toward.
-- ----------------------------------------------------------------------------
INSERT INTO facilities (facilities_id, facility_name, owner, type, town, region, lead_route, aligned, decision_maker, title, email, phone, website, status, next_step, fit_notes)
VALUES ('929bca66-3ca0-5642-c94d-8367611c6386', 'Mount Alverno', 'liz', NULL, 'Warwick', 'warwick-ny', 'warm-via-mina', 'unknown', NULL, NULL, NULL, NULL, NULL, 'to-research', 'Research the community and confirm the right contact', 'Early target in Warwick, alignment to be confirmed.') ON CONFLICT (facilities_id) DO NOTHING;

INSERT INTO facilities (facilities_id, facility_name, owner, type, town, region, lead_route, aligned, decision_maker, title, email, phone, website, status, next_step, fit_notes)
VALUES ('5745cec4-3c5e-b754-c995-042ff679c9dd', 'Unconfirmed Warwick target', 'liz', NULL, NULL, 'warwick-ny', 'warm-via-mina', 'unknown', NULL, NULL, NULL, NULL, NULL, 'to-research', NULL, 'Placeholder name to be resolved with Mina.') ON CONFLICT (facilities_id) DO NOTHING;

INSERT INTO facilities (facilities_id, facility_name, owner, type, town, region, lead_route, aligned, decision_maker, title, email, phone, website, status, next_step, fit_notes)
VALUES ('b38fdec1-d451-c19a-0b3a-78504fe4c2e7', 'Unconfirmed Goshen target', 'liz', NULL, NULL, 'goshen-ny', 'warm-via-mina', 'unknown', NULL, NULL, NULL, NULL, NULL, 'to-research', NULL, 'Placeholder name to be resolved with Mina.') ON CONFLICT (facilities_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Captures: Pain points, case studies, and ideas, captured as they come. Feeds the marketing package.
-- ----------------------------------------------------------------------------
INSERT INTO captures (captures_id, title, owner, type, detail)
VALUES ('653fd8f2-f43c-0b63-8aa3-c7b06c0d75b8', 'Families feel overwhelmed by later-life planning', 'liz', 'pain-point', 'Families often do not know where to begin with later-life planning and feel alone in it. A calm guide reduces the overwhelm.') ON CONFLICT (captures_id) DO NOTHING;

INSERT INTO captures (captures_id, title, owner, type, detail)
VALUES ('ac3249ad-fa68-c0ad-98ef-b5d5efdb7af0', 'Facilities want a warmer guide for residents and families', 'liz', 'pain-point', 'Communities want a gentle, human way to support residents and families through later-life planning and connection, led by community first rather than by clinical language.') ON CONFLICT (captures_id) DO NOTHING;

INSERT INTO captures (captures_id, title, owner, type, detail)
VALUES ('afb11519-37dc-80c8-2912-d792314da939', 'A Warwick family found calm through guided planning', 'liz', 'case-study', 'A local family moved from anxiety to calm by walking through their later-life plan with a trusted guide, one small step at a time.') ON CONFLICT (captures_id) DO NOTHING;

INSERT INTO captures (captures_id, title, owner, type, detail)
VALUES ('655488ec-ffb6-5e47-4ea8-d1a37e99063a', 'Monthly community gathering on living fully in later life', 'liz', 'idea', 'Host a warm monthly gathering at a partner facility focused on living fully in later life, legacy, and connection.') ON CONFLICT (captures_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Spheres: Controlled vocabulary for people.sphere. The part of the network a person belongs to. Generated as a derivative enum table. Do not hardcode these in the frontend or schema.
-- ----------------------------------------------------------------------------
INSERT INTO spheres (spheres_id, sphere_label, description, sort_order, people)
VALUES ('54f1083f-7295-5e0e-c37b-c1ffc634dcf1', 'Facility', 'A target facility or someone inside one.', 1, NULL) ON CONFLICT (spheres_id) DO NOTHING;

INSERT INTO spheres (spheres_id, sphere_label, description, sort_order, people)
VALUES ('c040f3f4-d38c-a559-a348-e59e03d37c20', 'Independent Living', 'Independent living communities and contacts.', 2, NULL) ON CONFLICT (spheres_id) DO NOTHING;

INSERT INTO spheres (spheres_id, sphere_label, description, sort_order, people)
VALUES ('08f6bbff-ebd8-2dae-bcff-3cfeb8c8b8e2', 'Community', 'Local community ecosystem.', 3, NULL) ON CONFLICT (spheres_id) DO NOTHING;

INSERT INTO spheres (spheres_id, sphere_label, description, sort_order, people)
VALUES ('526469dc-0d3b-e12e-f7a0-ccf501e8c04a', 'Nonprofit', 'Nonprofit organizations.', 4, NULL) ON CONFLICT (spheres_id) DO NOTHING;

INSERT INTO spheres (spheres_id, sphere_label, description, sort_order, people)
VALUES ('d7ca623e-7605-ba4d-9d60-01da5e8e3ed6', 'Foundation', 'Foundations and grantmakers.', 5, NULL) ON CONFLICT (spheres_id) DO NOTHING;

INSERT INTO spheres (spheres_id, sphere_label, description, sort_order, people)
VALUES ('9f516a8c-58eb-baf9-8e18-18288ce61b73', 'Faith Leader', 'Faith leaders and congregations.', 6, NULL) ON CONFLICT (spheres_id) DO NOTHING;

INSERT INTO spheres (spheres_id, sphere_label, description, sort_order, people)
VALUES ('4eed2bbc-1c20-b610-2beb-36a9854b4b1c', 'Insurance', 'Insurance and benefits contacts.', 7, NULL) ON CONFLICT (spheres_id) DO NOTHING;

INSERT INTO spheres (spheres_id, sphere_label, description, sort_order, people)
VALUES ('c500ba90-d7ad-e4d3-ef92-e7a46267186a', 'Doula', 'Doulas and care companions.', 8, NULL) ON CONFLICT (spheres_id) DO NOTHING;

INSERT INTO spheres (spheres_id, sphere_label, description, sort_order, people)
VALUES ('9b0853c9-1784-c413-d1cc-c8666f2dd83c', 'Legal', 'Legal and estate contacts.', 9, NULL) ON CONFLICT (spheres_id) DO NOTHING;

INSERT INTO spheres (spheres_id, sphere_label, description, sort_order, people)
VALUES ('6bcf05c3-20fb-88e6-f965-a3c26bbfb9ea', 'Mentor', 'Mentors and advisors.', 10, NULL) ON CONFLICT (spheres_id) DO NOTHING;

INSERT INTO spheres (spheres_id, sphere_label, description, sort_order, people)
VALUES ('78174fe5-a5e6-d519-f941-91cd81e649d3', 'Other', 'Anything that does not fit another sphere.', 11, NULL) ON CONFLICT (spheres_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- PersonStatuses: Controlled vocabulary for people.status. Where a relationship stands. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
INSERT INTO person_statuses (person_statuses_id, status_label, description, sort_order, people)
VALUES ('5db52db2-b6a1-64fc-427a-1c5acc36bee0', 'To reach out', 'Ready for a first warm hello.', 1, NULL) ON CONFLICT (person_statuses_id) DO NOTHING;

INSERT INTO person_statuses (person_statuses_id, status_label, description, sort_order, people)
VALUES ('bae8fcd9-97d9-7d8b-a2ed-f168d5f154f8', 'Reached out', 'A first hello has been sent.', 2, NULL) ON CONFLICT (person_statuses_id) DO NOTHING;

INSERT INTO person_statuses (person_statuses_id, status_label, description, sort_order, people)
VALUES ('cbcd6945-2312-2fd8-552b-8c47e2835945', 'In conversation', 'An active back and forth is underway.', 3, NULL) ON CONFLICT (person_statuses_id) DO NOTHING;

INSERT INTO person_statuses (person_statuses_id, status_label, description, sort_order, people)
VALUES ('3b9b01c4-61af-1c56-0bf6-05610e225428', 'Intro made', 'A warm introduction has been made.', 4, NULL) ON CONFLICT (person_statuses_id) DO NOTHING;

INSERT INTO person_statuses (person_statuses_id, status_label, description, sort_order, people)
VALUES ('94d2c067-f176-d44e-975a-785797029d17', 'Resting', 'Set aside gently for now, ready when the time is right.', 5, NULL) ON CONFLICT (person_statuses_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- FacilityTypes: Controlled vocabulary for facilities.type. The kind of place. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
INSERT INTO facility_types (facility_types_id, type_label, description, sort_order, facilities)
VALUES ('a372ae69-ec0d-0ccd-f6c4-863a6c9f8154', 'Independent Living', 'Independent living community.', 1, NULL) ON CONFLICT (facility_types_id) DO NOTHING;

INSERT INTO facility_types (facility_types_id, type_label, description, sort_order, facilities)
VALUES ('5fc7f647-94a3-d92b-c5e2-d5ca53eb0093', '55 and Over Community', 'Age qualified 55 and over community.', 2, NULL) ON CONFLICT (facility_types_id) DO NOTHING;

INSERT INTO facility_types (facility_types_id, type_label, description, sort_order, facilities)
VALUES ('e0ec927f-5e19-9fe6-52c9-5a8721d6a662', 'Assisted Living', 'Assisted living community.', 3, NULL) ON CONFLICT (facility_types_id) DO NOTHING;

INSERT INTO facility_types (facility_types_id, type_label, description, sort_order, facilities)
VALUES ('de9f075f-f3e0-3620-0270-eda781e16932', 'Memory Care', 'Memory care community.', 4, NULL) ON CONFLICT (facility_types_id) DO NOTHING;

INSERT INTO facility_types (facility_types_id, type_label, description, sort_order, facilities)
VALUES ('e2e29766-4014-be7c-e2af-091e97c055ea', 'Skilled Nursing', 'Skilled nursing facility.', 5, NULL) ON CONFLICT (facility_types_id) DO NOTHING;

INSERT INTO facility_types (facility_types_id, type_label, description, sort_order, facilities)
VALUES ('d07e82a3-9c4e-82e4-658a-22605648cf83', 'CCRC', 'Continuing care retirement community.', 6, NULL) ON CONFLICT (facility_types_id) DO NOTHING;

INSERT INTO facility_types (facility_types_id, type_label, description, sort_order, facilities)
VALUES ('972e37e4-738d-71c2-59c9-d500df8b017b', 'Senior Center', 'Senior center.', 7, NULL) ON CONFLICT (facility_types_id) DO NOTHING;

INSERT INTO facility_types (facility_types_id, type_label, description, sort_order, facilities)
VALUES ('2d87479c-0784-2daa-6bab-b19fd1c5711a', 'Other', 'Anything that does not fit another type.', 8, NULL) ON CONFLICT (facility_types_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Regions: Controlled vocabulary for facilities.region. Geographic grouping. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
INSERT INTO regions (regions_id, region_label, description, sort_order, facilities)
VALUES ('b6adad90-6b95-33de-9638-5661a533acc4', 'Warwick NY', 'Warwick, New York.', 1, NULL) ON CONFLICT (regions_id) DO NOTHING;

INSERT INTO regions (regions_id, region_label, description, sort_order, facilities)
VALUES ('b6cbe892-0368-d301-3238-18fa5ae8ce25', 'Goshen NY', 'Goshen, New York.', 2, NULL) ON CONFLICT (regions_id) DO NOTHING;

INSERT INTO regions (regions_id, region_label, description, sort_order, facilities)
VALUES ('df85b264-3401-1155-65c4-2540939db796', 'Orange County NY', 'Orange County, New York.', 3, NULL) ON CONFLICT (regions_id) DO NOTHING;

INSERT INTO regions (regions_id, region_label, description, sort_order, facilities)
VALUES ('a92569a7-3d4f-2f9a-903c-2f44d2dc187a', 'Rockland County NY', 'Rockland County, New York.', 4, NULL) ON CONFLICT (regions_id) DO NOTHING;

INSERT INTO regions (regions_id, region_label, description, sort_order, facilities)
VALUES ('9272af06-a6aa-f9f6-d5db-ec7bed4fdff0', 'Sussex County NJ', 'Sussex County, New Jersey.', 5, NULL) ON CONFLICT (regions_id) DO NOTHING;

INSERT INTO regions (regions_id, region_label, description, sort_order, facilities)
VALUES ('6fa108be-4291-1d10-a26e-e4614a64a74f', 'Other', 'Anywhere else.', 6, NULL) ON CONFLICT (regions_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- LeadRoutes: Controlled vocabulary for facilities.lead_route. How Liz can reach a facility. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
INSERT INTO lead_routes (lead_routes_id, lead_route_label, description, sort_order, facilities)
VALUES ('fe093a38-da24-3434-f717-212a6f840bf5', 'Warm via Mina', 'Warm introduction through Mina.', 1, NULL) ON CONFLICT (lead_routes_id) DO NOTHING;

INSERT INTO lead_routes (lead_routes_id, lead_route_label, description, sort_order, facilities)
VALUES ('f9016aa5-1b0d-a66b-5573-47c8e2ce8be5', 'Warm via Haley', 'Warm introduction through Haley.', 2, NULL) ON CONFLICT (lead_routes_id) DO NOTHING;

INSERT INTO lead_routes (lead_routes_id, lead_route_label, description, sort_order, facilities)
VALUES ('d4654f68-fec5-bc57-1676-83a131bf707a', 'Warm via other', 'Warm introduction through another connector.', 3, NULL) ON CONFLICT (lead_routes_id) DO NOTHING;

INSERT INTO lead_routes (lead_routes_id, lead_route_label, description, sort_order, facilities)
VALUES ('6968a22e-5d32-62f8-1eea-6dfbc376692d', 'Cold', 'No warm route yet, a cold approach.', 4, NULL) ON CONFLICT (lead_routes_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- AlignmentLevels: Controlled vocabulary for facilities.aligned. Whether a facility seems values aligned. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
INSERT INTO alignment_levels (alignment_levels_id, alignment_label, description, sort_order, facilities)
VALUES ('2d6aa0f8-1983-a67a-4a0e-76ca7ca5b951', 'Yes', 'Clearly values aligned.', 1, NULL) ON CONFLICT (alignment_levels_id) DO NOTHING;

INSERT INTO alignment_levels (alignment_levels_id, alignment_label, description, sort_order, facilities)
VALUES ('a918d64d-fbcd-3671-c44b-2f3479c9f9d6', 'Maybe', 'Possibly aligned, needs a closer look.', 2, NULL) ON CONFLICT (alignment_levels_id) DO NOTHING;

INSERT INTO alignment_levels (alignment_levels_id, alignment_label, description, sort_order, facilities)
VALUES ('35ecbd03-5dfa-1aee-8a72-c1c379688dd4', 'No', 'Not a values fit.', 3, NULL) ON CONFLICT (alignment_levels_id) DO NOTHING;

INSERT INTO alignment_levels (alignment_levels_id, alignment_label, description, sort_order, facilities)
VALUES ('07a40858-9016-5dac-10f5-98cbfaea5c43', 'Unknown', 'Not yet assessed.', 4, NULL) ON CONFLICT (alignment_levels_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- FacilityStatuses: Controlled vocabulary for facilities.status. Where the outreach stands. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
INSERT INTO facility_statuses (facility_statuses_id, status_label, description, sort_order, facilities)
VALUES ('776f7650-cf15-75d0-2371-7da2df26d815', 'To research', 'Identified, not yet researched.', 1, NULL) ON CONFLICT (facility_statuses_id) DO NOTHING;

INSERT INTO facility_statuses (facility_statuses_id, status_label, description, sort_order, facilities)
VALUES ('ecb009c2-7834-4979-852e-a6a27cd1c3c8', 'Intro requested', 'A warm introduction has been requested.', 2, NULL) ON CONFLICT (facility_statuses_id) DO NOTHING;

INSERT INTO facility_statuses (facility_statuses_id, status_label, description, sort_order, facilities)
VALUES ('91efb645-1577-648b-66f4-0aa8818ac02d', 'Meeting set', 'A meeting is on the calendar.', 3, NULL) ON CONFLICT (facility_statuses_id) DO NOTHING;

INSERT INTO facility_statuses (facility_statuses_id, status_label, description, sort_order, facilities)
VALUES ('61514df3-1cdf-f64f-3d0f-895590695aef', 'In discussion', 'An active discussion is underway.', 4, NULL) ON CONFLICT (facility_statuses_id) DO NOTHING;

INSERT INTO facility_statuses (facility_statuses_id, status_label, description, sort_order, facilities)
VALUES ('4121de53-c668-5051-c837-acf46ac0fc31', 'Proposal sent', 'A proposal has been shared.', 5, NULL) ON CONFLICT (facility_statuses_id) DO NOTHING;

INSERT INTO facility_statuses (facility_statuses_id, status_label, description, sort_order, facilities)
VALUES ('949a6826-35e1-57cf-f8f2-299d3bac74d3', 'Signed', 'A partnership is in place.', 6, NULL) ON CONFLICT (facility_statuses_id) DO NOTHING;

INSERT INTO facility_statuses (facility_statuses_id, status_label, description, sort_order, facilities)
VALUES ('2b021e54-ab92-84b6-3095-91c9879a2d38', 'Resting', 'Set aside gently for now.', 7, NULL) ON CONFLICT (facility_statuses_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- CaptureTypes: Controlled vocabulary for captures.type. The kind of capture. Generated as a derivative enum table.
-- ----------------------------------------------------------------------------
INSERT INTO capture_types (capture_types_id, type_label, description, sort_order, captures)
VALUES ('02debdb7-1061-b75f-c3a5-1ed48bc48148', 'Pain Point', 'A problem or frustration worth solving.', 1, NULL) ON CONFLICT (capture_types_id) DO NOTHING;

INSERT INTO capture_types (capture_types_id, type_label, description, sort_order, captures)
VALUES ('43800e50-ca84-204c-789b-bbdce725a83d', 'Case Study', 'A real story of someone helped.', 2, NULL) ON CONFLICT (capture_types_id) DO NOTHING;

INSERT INTO capture_types (capture_types_id, type_label, description, sort_order, captures)
VALUES ('f1680bac-08ff-99a2-dd68-808ea39401c9', 'Idea', 'An idea to explore later.', 3, NULL) ON CONFLICT (capture_types_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- WarmthLevels: Controlled vocabulary for the derived warmth value. Warmth is computed from LastTouched and is not stored. These rows give the frontend the labels and gentle framing for each level. See GovernanceRules R2 and R5.
-- ----------------------------------------------------------------------------
INSERT INTO warmth_levels (warmth_levels_id, warmth_label, description, guidance, sort_order)
VALUES ('1824fc9f-f7bc-4614-86ad-bd168b7aa09c', 'Warm', 'Touched within the warm threshold.', 'Recently connected.', 1) ON CONFLICT (warmth_levels_id) DO NOTHING;

INSERT INTO warmth_levels (warmth_levels_id, warmth_label, description, guidance, sort_order)
VALUES ('20a0c96a-cc3a-fb53-65d7-7635186790fb', 'Cooling', 'Between the warm and cooling thresholds.', 'A good time for a gentle hello.', 2) ON CONFLICT (warmth_levels_id) DO NOTHING;

INSERT INTO warmth_levels (warmth_levels_id, warmth_label, description, guidance, sort_order)
VALUES ('25914ccf-5224-c33b-431a-07857c0b14d0', 'Cold', 'Beyond the cooling threshold or never touched.', 'Ready for a hello.', 3) ON CONFLICT (warmth_levels_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- GovernanceRules: The governance rules for the BeaconHaus Companion, one row per rule. Each rule is meaning that lives in the rulebook and is traceable. The frontend and backend enforce these because they are generated from them, not because someone wrote them into code by hand.
-- ----------------------------------------------------------------------------
INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('9edf5272-cad1-5d29-ee87-d42fd399a6f4', 'R1', 'Ownership', 'Every row belongs to one user through the Owner relationship to Profiles. Row Level Security limits all access to that user. Realized in the generated RLS policies.', 'Ownership', 'Generated RLS policies, keyed off the Owner relationship', 1) ON CONFLICT (governance_rules_id) DO NOTHING;

INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('cf94013f-352d-0cdc-6696-3da5264a1bf5', 'R2', 'Warmth Model', 'Warmth is derived from LastTouched. A person is Warm within WarmThresholdDays, Cooling up to CoolingThresholdDays, and Cold beyond that or when never touched. Warmth drives sorting and the daily ritual only.', 'Warmth', 'People.Warmth calculated field and the threshold lookups', 2) ON CONFLICT (governance_rules_id) DO NOTHING;

INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('aae4de6d-41b8-f2a6-3307-d6964823bee6', 'R3', 'Daily Ritual', 'The Today screen surfaces MorningWarmupCount people, coldest or never touched first, one at a time. Logging a hello sets LastTouched to today and counts toward the weekly total.', 'Ritual', 'App Today screen and Profiles.MorningWarmupCount', 3) ON CONFLICT (governance_rules_id) DO NOTHING;

INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('188a53ff-c5f7-a31a-379f-65040f58b529', 'R4', 'Weekly Count', 'The weekly count is counted since the most recent Monday and resets each Monday. It is shown as encouragement toward WeeklyWarmupGoal, never as a backlog.', 'Ritual', 'App weekly counter, Profiles.WeekStart and Profiles.WeekCount', 4) ON CONFLICT (governance_rules_id) DO NOTHING;

INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('85c00bd8-f60f-d5c8-6440-09f391c1687e', 'R5', 'No Guilt', 'No overdue, late, or warning states anywhere. A cold contact reads as ready for a hello. Empty states are warm and inviting.', 'UX', 'App copy and WarmthLevels guidance', 5) ON CONFLICT (governance_rules_id) DO NOTHING;

INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('a12946e2-bb88-815c-1755-d62dcee05c5d', 'R6', 'Minimal Friction', 'Only FullName for a person or FacilityName for a facility is required to create a row. Every other field is optional.', 'UX', 'Field nullability, only the Name source fields are required', 6) ON CONFLICT (governance_rules_id) DO NOTHING;

INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('96e89f01-ab3a-6dee-1bc6-c84e1a71cbbd', 'R7', 'Status Auto Advance', 'Logging a first hello moves a person from To reach out to Reached out. Further status changes are manual.', 'Workflow', 'App mutation on the first logged hello', 7) ON CONFLICT (governance_rules_id) DO NOTHING;

INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('59981d31-eecd-18ad-87a2-ed7444434d81', 'R8', 'Content Punctuation', 'Never use em dashes or en dashes in any label, message, or generated text. Use hyphens only inside hyphenated words. This is a BeaconHaus content rule.', 'Content', 'Content generation and all labels', 8) ON CONFLICT (governance_rules_id) DO NOTHING;

INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('2a67cf5f-eca4-a8af-b821-8534322ea411', 'R9', 'Positioning', 'Do not lead with death literacy in the interface. Lead with later-life planning and community connection.', 'Positioning', 'App copy and positioning', 9) ON CONFLICT (governance_rules_id) DO NOTHING;

INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('ffc5ba00-40e4-bbf8-b209-90ce1a9fcf77', 'R10', 'LinkedIn Safety', 'No scraping or browser automation of LinkedIn, ever. The official API cannot read connections, search people, or send requests or messages for this app, and unofficial tools risk her account. LinkedIn is limited to official posting through the member social scope and Open in LinkedIn deep links from stored profile URLs.', 'Integration', 'Integration layer, posting and deep links only', 10) ON CONFLICT (governance_rules_id) DO NOTHING;

INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('a4f7bcd0-5f2a-8e9e-c29a-15d8e5042119', 'R11', 'Least Privilege', 'Request the narrowest OAuth scope that does the job: drive.file for Drive, calendar.events for Calendar, member social for LinkedIn posting, and Gmail send only if added later. Ask for each scope only when the feature is first used.', 'Security', 'OAuth consent flow with incremental scopes', 11) ON CONFLICT (governance_rules_id) DO NOTHING;

INSERT INTO governance_rules (governance_rules_id, rule_code, title, statement, category, enforced_by, sort_order)
VALUES ('5193737d-feb4-ae96-f1a2-58dcfddb1cf7', 'R12', 'Secrets Server Side', 'OAuth client secrets and token exchanges live only in server code. Tokens are stored in OAuthTokens, never in the client bundle.', 'Security', 'Server routes and OAuthTokens storage', 12) ON CONFLICT (governance_rules_id) DO NOTHING;

