-- ============================================================================
-- CUSTOMIZE DATA - User-defined data customizations
-- ============================================================================
-- This file is for YOUR custom changes that should persist across
-- regeneration of the base ERB files.
--
-- IMPORTANT:
--   - This file runs AFTER the main data script
--   - Define your customizations in the ERBCustomizations table in Airtable
--   - Those changes will appear here after the next build
--
-- ============================================================================

-- Your custom data changes will appear here:

-- Before Liz signs in with Google for the first time, add one claim row that
-- maps her email address to the existing ERB seed profile.
--
-- Example:
-- INSERT INTO beaconhaus_profile_claims (email, account_key)
-- VALUES ('liz@example.com', 'liz')
-- ON CONFLICT (email) DO UPDATE SET account_key = EXCLUDED.account_key;
